// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.Empty)
    com.google.protobuf.MessageOrBuilder {
}
