// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public final class NotifyProto extends com.google.protobuf.GeneratedFile {
  private NotifyProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "NotifyProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_Pong_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_Pong_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_Options_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_Options_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PublishRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PublishRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PublishRequest_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PublishRequest_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PublishAck_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PublishAck_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_SubscribeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_SubscribeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_Event_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_Event_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_Event_ParamsEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_Event_ParamsEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PlatformConfig_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PlatformConfig_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PlatformConfig_ExtraEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PlatformConfig_ExtraEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_RetryPolicy_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_RetryPolicy_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PlatformRef_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PlatformRef_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_notify_v1_PlatformList_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_notify_v1_PlatformList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026notify/v1/notify.proto\022\tnotify.v1\"\007\n\005E" +
      "mpty\"/\n\004Pong\022\017\n\007version\030\001 \001(\t\022\026\n\016uptime_" +
      "seconds\030\002 \001(\003\"N\n\007Options\022\021\n\tdedup_key\030\001 " +
      "\001(\t\022\030\n\020skip_subscribers\030\002 \001(\010\022\026\n\016skip_pl" +
      "atforms\030\003 \001(\010\"\335\001\n\016PublishRequest\022\r\n\005topi" +
      "c\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\017\n\007content\030\003 \001(\t\022" +
      "5\n\006params\030\004 \003(\0132%.notify.v1.PublishReque" +
      "st.ParamsEntry\022\021\n\tplatforms\030\005 \003(\t\022#\n\007opt" +
      "ions\030\006 \001(\0132\022.notify.v1.Options\032-\n\013Params" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"p\n" +
      "\nPublishAck\022\020\n\010event_id\030\001 \001(\t\022\020\n\010accepte" +
      "d\030\002 \001(\010\022\024\n\014deduplicated\030\003 \001(\010\022\031\n\021matched" +
      "_platforms\030\004 \003(\t\022\r\n\005error\030\005 \001(\t\"\"\n\020Subsc" +
      "ribeRequest\022\016\n\006topics\030\001 \003(\t\"\312\001\n\005Event\022\r\n" +
      "\005topic\030\001 \001(\t\022\r\n\005title\030\002 \001(\t\022\017\n\007content\030\003" +
      " \001(\t\022,\n\006params\030\004 \003(\0132\034.notify.v1.Event.P" +
      "aramsEntry\022\020\n\010platform\030\005 \001(\t\022\020\n\010event_id" +
      "\030\006 \001(\t\022\021\n\ttimestamp\030\007 \001(\003\032-\n\013ParamsEntry" +
      "\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001\"\245\002\n\016Pla" +
      "tformConfig\022\014\n\004name\030\001 \001(\t\022\014\n\004type\030\002 \001(\t\022" +
      "\017\n\007webhook\030\003 \001(\t\022\016\n\006secret\030\004 \001(\t\022\016\n\006topi" +
      "cs\030\005 \003(\t\022\020\n\010template\030\006 \001(\t\022\022\n\nat_mobiles" +
      "\030\007 \003(\t\0223\n\005extra\030\010 \003(\0132$.notify.v1.Platfo" +
      "rmConfig.ExtraEntry\022%\n\005retry\030\t \001(\0132\026.not" +
      "ify.v1.RetryPolicy\022\026\n\016rate_limit_qps\030\n \001" +
      "(\005\032,\n\nExtraEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002" +
      " \001(\t:\0028\001\"7\n\013RetryPolicy\022\024\n\014max_attempts\030" +
      "\001 \001(\005\022\022\n\nbackoff_ms\030\002 \001(\003\"\033\n\013PlatformRef" +
      "\022\014\n\004name\030\001 \001(\t\"<\n\014PlatformList\022,\n\tplatfo" +
      "rms\030\001 \003(\0132\031.notify.v1.PlatformConfig2\265\003\n" +
      "\006Notify\022;\n\007Publish\022\031.notify.v1.PublishRe" +
      "quest\032\025.notify.v1.PublishAck\022<\n\tSubscrib" +
      "e\022\033.notify.v1.SubscribeRequest\032\020.notify." +
      "v1.Event0\001\022E\n\rPublishStream\022\031.notify.v1." +
      "PublishRequest\032\025.notify.v1.PublishAck(\0010" +
      "\001\022F\n\016UpsertPlatform\022\031.notify.v1.Platform" +
      "Config\032\031.notify.v1.PlatformConfig\022:\n\rLis" +
      "tPlatforms\022\020.notify.v1.Empty\032\027.notify.v1" +
      ".PlatformList\022:\n\016RemovePlatform\022\026.notify" +
      ".v1.PlatformRef\032\020.notify.v1.Empty\022)\n\004Pin" +
      "g\022\020.notify.v1.Empty\032\017.notify.v1.PongBc\n\017" +
      "io.notifyhub.v1B\013NotifyProtoP\001ZAgithub.c" +
      "om/huangwenfu750/notifyhub/sdks/go/gen/n" +
      "otify/v1;notifyv1b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_notify_v1_Empty_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_notify_v1_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_notify_v1_Pong_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_notify_v1_Pong_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_Pong_descriptor,
        new java.lang.String[] { "Version", "UptimeSeconds", });
    internal_static_notify_v1_Options_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_notify_v1_Options_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_Options_descriptor,
        new java.lang.String[] { "DedupKey", "SkipSubscribers", "SkipPlatforms", });
    internal_static_notify_v1_PublishRequest_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_notify_v1_PublishRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PublishRequest_descriptor,
        new java.lang.String[] { "Topic", "Title", "Content", "Params", "Platforms", "Options", });
    internal_static_notify_v1_PublishRequest_ParamsEntry_descriptor =
      internal_static_notify_v1_PublishRequest_descriptor.getNestedType(0);
    internal_static_notify_v1_PublishRequest_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PublishRequest_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_notify_v1_PublishAck_descriptor =
      getDescriptor().getMessageType(4);
    internal_static_notify_v1_PublishAck_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PublishAck_descriptor,
        new java.lang.String[] { "EventId", "Accepted", "Deduplicated", "MatchedPlatforms", "Error", });
    internal_static_notify_v1_SubscribeRequest_descriptor =
      getDescriptor().getMessageType(5);
    internal_static_notify_v1_SubscribeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_SubscribeRequest_descriptor,
        new java.lang.String[] { "Topics", });
    internal_static_notify_v1_Event_descriptor =
      getDescriptor().getMessageType(6);
    internal_static_notify_v1_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_Event_descriptor,
        new java.lang.String[] { "Topic", "Title", "Content", "Params", "Platform", "EventId", "Timestamp", });
    internal_static_notify_v1_Event_ParamsEntry_descriptor =
      internal_static_notify_v1_Event_descriptor.getNestedType(0);
    internal_static_notify_v1_Event_ParamsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_Event_ParamsEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_notify_v1_PlatformConfig_descriptor =
      getDescriptor().getMessageType(7);
    internal_static_notify_v1_PlatformConfig_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PlatformConfig_descriptor,
        new java.lang.String[] { "Name", "Type", "Webhook", "Secret", "Topics", "Template", "AtMobiles", "Extra", "Retry", "RateLimitQps", });
    internal_static_notify_v1_PlatformConfig_ExtraEntry_descriptor =
      internal_static_notify_v1_PlatformConfig_descriptor.getNestedType(0);
    internal_static_notify_v1_PlatformConfig_ExtraEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PlatformConfig_ExtraEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
    internal_static_notify_v1_RetryPolicy_descriptor =
      getDescriptor().getMessageType(8);
    internal_static_notify_v1_RetryPolicy_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_RetryPolicy_descriptor,
        new java.lang.String[] { "MaxAttempts", "BackoffMs", });
    internal_static_notify_v1_PlatformRef_descriptor =
      getDescriptor().getMessageType(9);
    internal_static_notify_v1_PlatformRef_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PlatformRef_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_notify_v1_PlatformList_descriptor =
      getDescriptor().getMessageType(10);
    internal_static_notify_v1_PlatformList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_notify_v1_PlatformList_descriptor,
        new java.lang.String[] { "Platforms", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
