// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

/**
 * Protobuf type {@code notify.v1.Options}
 */
@com.google.protobuf.Generated
public final class Options extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notify.v1.Options)
    OptionsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "Options");
  }
  // Use Options.newBuilder() to construct.
  private Options(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Options() {
    dedupKey_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_Options_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_Options_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_Options_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.notifyhub.v1.Options.class, io.notifyhub.v1.Options.Builder.class);
  }

  public static final int DEDUP_KEY_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object dedupKey_ = "";
  /**
   * <pre>
   * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
   * </pre>
   *
   * <code>string dedup_key = 1;</code>
   * @return The dedupKey.
   */
  @java.lang.Override
  public java.lang.String getDedupKey() {
    java.lang.Object ref = dedupKey_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      dedupKey_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
   * </pre>
   *
   * <code>string dedup_key = 1;</code>
   * @return The bytes for dedupKey.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDedupKeyBytes() {
    java.lang.Object ref = dedupKey_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      dedupKey_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKIP_SUBSCRIBERS_FIELD_NUMBER = 2;
  private boolean skipSubscribers_ = false;
  /**
   * <pre>
   * 不广播给在线订阅者
   * </pre>
   *
   * <code>bool skip_subscribers = 2;</code>
   * @return The skipSubscribers.
   */
  @java.lang.Override
  public boolean getSkipSubscribers() {
    return skipSubscribers_;
  }

  public static final int SKIP_PLATFORMS_FIELD_NUMBER = 3;
  private boolean skipPlatforms_ = false;
  /**
   * <pre>
   * 不推送到外部平台
   * </pre>
   *
   * <code>bool skip_platforms = 3;</code>
   * @return The skipPlatforms.
   */
  @java.lang.Override
  public boolean getSkipPlatforms() {
    return skipPlatforms_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dedupKey_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, dedupKey_);
    }
    if (skipSubscribers_ != false) {
      output.writeBool(2, skipSubscribers_);
    }
    if (skipPlatforms_ != false) {
      output.writeBool(3, skipPlatforms_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(dedupKey_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, dedupKey_);
    }
    if (skipSubscribers_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, skipSubscribers_);
    }
    if (skipPlatforms_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, skipPlatforms_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.notifyhub.v1.Options)) {
      return super.equals(obj);
    }
    io.notifyhub.v1.Options other = (io.notifyhub.v1.Options) obj;

    if (!getDedupKey()
        .equals(other.getDedupKey())) return false;
    if (getSkipSubscribers()
        != other.getSkipSubscribers()) return false;
    if (getSkipPlatforms()
        != other.getSkipPlatforms()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + DEDUP_KEY_FIELD_NUMBER;
    hash = (53 * hash) + getDedupKey().hashCode();
    hash = (37 * hash) + SKIP_SUBSCRIBERS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkipSubscribers());
    hash = (37 * hash) + SKIP_PLATFORMS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSkipPlatforms());
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.notifyhub.v1.Options parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.Options parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.Options parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.Options parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.Options parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.Options parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.Options parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.Options parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.notifyhub.v1.Options parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.notifyhub.v1.Options parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.notifyhub.v1.Options parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.Options parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.notifyhub.v1.Options prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notify.v1.Options}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notify.v1.Options)
      io.notifyhub.v1.OptionsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_Options_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_Options_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.notifyhub.v1.Options.class, io.notifyhub.v1.Options.Builder.class);
    }

    // Construct using io.notifyhub.v1.Options.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      dedupKey_ = "";
      skipSubscribers_ = false;
      skipPlatforms_ = false;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_Options_descriptor;
    }

    @java.lang.Override
    public io.notifyhub.v1.Options getDefaultInstanceForType() {
      return io.notifyhub.v1.Options.getDefaultInstance();
    }

    @java.lang.Override
    public io.notifyhub.v1.Options build() {
      io.notifyhub.v1.Options result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.notifyhub.v1.Options buildPartial() {
      io.notifyhub.v1.Options result = new io.notifyhub.v1.Options(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.notifyhub.v1.Options result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.dedupKey_ = dedupKey_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.skipSubscribers_ = skipSubscribers_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.skipPlatforms_ = skipPlatforms_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.notifyhub.v1.Options) {
        return mergeFrom((io.notifyhub.v1.Options)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.notifyhub.v1.Options other) {
      if (other == io.notifyhub.v1.Options.getDefaultInstance()) return this;
      if (!other.getDedupKey().isEmpty()) {
        dedupKey_ = other.dedupKey_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getSkipSubscribers() != false) {
        setSkipSubscribers(other.getSkipSubscribers());
      }
      if (other.getSkipPlatforms() != false) {
        setSkipPlatforms(other.getSkipPlatforms());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              dedupKey_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              skipSubscribers_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              skipPlatforms_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object dedupKey_ = "";
    /**
     * <pre>
     * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
     * </pre>
     *
     * <code>string dedup_key = 1;</code>
     * @return The dedupKey.
     */
    public java.lang.String getDedupKey() {
      java.lang.Object ref = dedupKey_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dedupKey_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
     * </pre>
     *
     * <code>string dedup_key = 1;</code>
     * @return The bytes for dedupKey.
     */
    public com.google.protobuf.ByteString
        getDedupKeyBytes() {
      java.lang.Object ref = dedupKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dedupKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
     * </pre>
     *
     * <code>string dedup_key = 1;</code>
     * @param value The dedupKey to set.
     * @return This builder for chaining.
     */
    public Builder setDedupKey(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      dedupKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
     * </pre>
     *
     * <code>string dedup_key = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDedupKey() {
      dedupKey_ = getDefaultInstance().getDedupKey();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
     * </pre>
     *
     * <code>string dedup_key = 1;</code>
     * @param value The bytes for dedupKey to set.
     * @return This builder for chaining.
     */
    public Builder setDedupKeyBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      dedupKey_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean skipSubscribers_ ;
    /**
     * <pre>
     * 不广播给在线订阅者
     * </pre>
     *
     * <code>bool skip_subscribers = 2;</code>
     * @return The skipSubscribers.
     */
    @java.lang.Override
    public boolean getSkipSubscribers() {
      return skipSubscribers_;
    }
    /**
     * <pre>
     * 不广播给在线订阅者
     * </pre>
     *
     * <code>bool skip_subscribers = 2;</code>
     * @param value The skipSubscribers to set.
     * @return This builder for chaining.
     */
    public Builder setSkipSubscribers(boolean value) {

      skipSubscribers_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 不广播给在线订阅者
     * </pre>
     *
     * <code>bool skip_subscribers = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipSubscribers() {
      bitField0_ = (bitField0_ & ~0x00000002);
      skipSubscribers_ = false;
      onChanged();
      return this;
    }

    private boolean skipPlatforms_ ;
    /**
     * <pre>
     * 不推送到外部平台
     * </pre>
     *
     * <code>bool skip_platforms = 3;</code>
     * @return The skipPlatforms.
     */
    @java.lang.Override
    public boolean getSkipPlatforms() {
      return skipPlatforms_;
    }
    /**
     * <pre>
     * 不推送到外部平台
     * </pre>
     *
     * <code>bool skip_platforms = 3;</code>
     * @param value The skipPlatforms to set.
     * @return This builder for chaining.
     */
    public Builder setSkipPlatforms(boolean value) {

      skipPlatforms_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 不推送到外部平台
     * </pre>
     *
     * <code>bool skip_platforms = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSkipPlatforms() {
      bitField0_ = (bitField0_ & ~0x00000004);
      skipPlatforms_ = false;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:notify.v1.Options)
  }

  // @@protoc_insertion_point(class_scope:notify.v1.Options)
  private static final io.notifyhub.v1.Options DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.notifyhub.v1.Options();
  }

  public static io.notifyhub.v1.Options getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Options>
      PARSER = new com.google.protobuf.AbstractParser<Options>() {
    @java.lang.Override
    public Options parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Options> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Options> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.notifyhub.v1.Options getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

