// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface OptionsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.Options)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
   * </pre>
   *
   * <code>string dedup_key = 1;</code>
   * @return The dedupKey.
   */
  java.lang.String getDedupKey();
  /**
   * <pre>
   * 去重键：窗口期内携带相同 key 的发布将不被投递（accepted=false, deduplicated=true）。
   * </pre>
   *
   * <code>string dedup_key = 1;</code>
   * @return The bytes for dedupKey.
   */
  com.google.protobuf.ByteString
      getDedupKeyBytes();

  /**
   * <pre>
   * 不广播给在线订阅者
   * </pre>
   *
   * <code>bool skip_subscribers = 2;</code>
   * @return The skipSubscribers.
   */
  boolean getSkipSubscribers();

  /**
   * <pre>
   * 不推送到外部平台
   * </pre>
   *
   * <code>bool skip_platforms = 3;</code>
   * @return The skipPlatforms.
   */
  boolean getSkipPlatforms();
}
