// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

/**
 * Protobuf type {@code notify.v1.PlatformList}
 */
@com.google.protobuf.Generated
public final class PlatformList extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notify.v1.PlatformList)
    PlatformListOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "PlatformList");
  }
  // Use PlatformList.newBuilder() to construct.
  private PlatformList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlatformList() {
    platforms_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformList_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformList_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformList_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.notifyhub.v1.PlatformList.class, io.notifyhub.v1.PlatformList.Builder.class);
  }

  public static final int PLATFORMS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<io.notifyhub.v1.PlatformConfig> platforms_;
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  @java.lang.Override
  public java.util.List<io.notifyhub.v1.PlatformConfig> getPlatformsList() {
    return platforms_;
  }
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends io.notifyhub.v1.PlatformConfigOrBuilder> 
      getPlatformsOrBuilderList() {
    return platforms_;
  }
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  @java.lang.Override
  public int getPlatformsCount() {
    return platforms_.size();
  }
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  @java.lang.Override
  public io.notifyhub.v1.PlatformConfig getPlatforms(int index) {
    return platforms_.get(index);
  }
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  @java.lang.Override
  public io.notifyhub.v1.PlatformConfigOrBuilder getPlatformsOrBuilder(
      int index) {
    return platforms_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < platforms_.size(); i++) {
      output.writeMessage(1, platforms_.get(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;

        {
          final int count = platforms_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(platforms_.get(i));
          }
          size += 1 * count;
        }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.notifyhub.v1.PlatformList)) {
      return super.equals(obj);
    }
    io.notifyhub.v1.PlatformList other = (io.notifyhub.v1.PlatformList) obj;

    if (!getPlatformsList()
        .equals(other.getPlatformsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPlatformsCount() > 0) {
      hash = (37 * hash) + PLATFORMS_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.notifyhub.v1.PlatformList parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.notifyhub.v1.PlatformList parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.notifyhub.v1.PlatformList parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PlatformList parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.notifyhub.v1.PlatformList prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notify.v1.PlatformList}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notify.v1.PlatformList)
      io.notifyhub.v1.PlatformListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.notifyhub.v1.PlatformList.class, io.notifyhub.v1.PlatformList.Builder.class);
    }

    // Construct using io.notifyhub.v1.PlatformList.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (platformsBuilder_ == null) {
        platforms_ = java.util.Collections.emptyList();
      } else {
        platforms_ = null;
        platformsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformList_descriptor;
    }

    @java.lang.Override
    public io.notifyhub.v1.PlatformList getDefaultInstanceForType() {
      return io.notifyhub.v1.PlatformList.getDefaultInstance();
    }

    @java.lang.Override
    public io.notifyhub.v1.PlatformList build() {
      io.notifyhub.v1.PlatformList result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.notifyhub.v1.PlatformList buildPartial() {
      io.notifyhub.v1.PlatformList result = new io.notifyhub.v1.PlatformList(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(io.notifyhub.v1.PlatformList result) {
      if (platformsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          platforms_ = java.util.Collections.unmodifiableList(platforms_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.platforms_ = platforms_;
      } else {
        result.platforms_ = platformsBuilder_.build();
      }
    }

    private void buildPartial0(io.notifyhub.v1.PlatformList result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.notifyhub.v1.PlatformList) {
        return mergeFrom((io.notifyhub.v1.PlatformList)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.notifyhub.v1.PlatformList other) {
      if (other == io.notifyhub.v1.PlatformList.getDefaultInstance()) return this;
      if (platformsBuilder_ == null) {
        if (!other.platforms_.isEmpty()) {
          if (platforms_.isEmpty()) {
            platforms_ = other.platforms_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePlatformsIsMutable();
            platforms_.addAll(other.platforms_);
          }
          onChanged();
        }
      } else {
        if (!other.platforms_.isEmpty()) {
          if (platformsBuilder_.isEmpty()) {
            platformsBuilder_.dispose();
            platformsBuilder_ = null;
            platforms_ = other.platforms_;
            bitField0_ = (bitField0_ & ~0x00000001);
            platformsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPlatformsFieldBuilder() : null;
          } else {
            platformsBuilder_.addAllMessages(other.platforms_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              io.notifyhub.v1.PlatformConfig m =
                  input.readMessage(
                      io.notifyhub.v1.PlatformConfig.parser(),
                      extensionRegistry);
              if (platformsBuilder_ == null) {
                ensurePlatformsIsMutable();
                platforms_.add(m);
              } else {
                platformsBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<io.notifyhub.v1.PlatformConfig> platforms_ =
      java.util.Collections.emptyList();
    private void ensurePlatformsIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        platforms_ = new java.util.ArrayList<io.notifyhub.v1.PlatformConfig>(platforms_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        io.notifyhub.v1.PlatformConfig, io.notifyhub.v1.PlatformConfig.Builder, io.notifyhub.v1.PlatformConfigOrBuilder> platformsBuilder_;

    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public java.util.List<io.notifyhub.v1.PlatformConfig> getPlatformsList() {
      if (platformsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(platforms_);
      } else {
        return platformsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public int getPlatformsCount() {
      if (platformsBuilder_ == null) {
        return platforms_.size();
      } else {
        return platformsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public io.notifyhub.v1.PlatformConfig getPlatforms(int index) {
      if (platformsBuilder_ == null) {
        return platforms_.get(index);
      } else {
        return platformsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder setPlatforms(
        int index, io.notifyhub.v1.PlatformConfig value) {
      if (platformsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensurePlatformsIsMutable();
        platforms_.set(index, value);
        onChanged();
      } else {
        platformsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder setPlatforms(
        int index, io.notifyhub.v1.PlatformConfig.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.set(index, builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder addPlatforms(io.notifyhub.v1.PlatformConfig value) {
      if (platformsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensurePlatformsIsMutable();
        platforms_.add(value);
        onChanged();
      } else {
        platformsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder addPlatforms(
        int index, io.notifyhub.v1.PlatformConfig value) {
      if (platformsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        ensurePlatformsIsMutable();
        platforms_.add(index, value);
        onChanged();
      } else {
        platformsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder addPlatforms(
        io.notifyhub.v1.PlatformConfig.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.add(builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder addPlatforms(
        int index, io.notifyhub.v1.PlatformConfig.Builder builderForValue) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.add(index, builderForValue.build());
        onChanged();
      } else {
        platformsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder addAllPlatforms(
        java.lang.Iterable<? extends io.notifyhub.v1.PlatformConfig> values) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, platforms_);
        onChanged();
      } else {
        platformsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder clearPlatforms() {
      if (platformsBuilder_ == null) {
        platforms_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        platformsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public Builder removePlatforms(int index) {
      if (platformsBuilder_ == null) {
        ensurePlatformsIsMutable();
        platforms_.remove(index);
        onChanged();
      } else {
        platformsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public io.notifyhub.v1.PlatformConfig.Builder getPlatformsBuilder(
        int index) {
      return internalGetPlatformsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public io.notifyhub.v1.PlatformConfigOrBuilder getPlatformsOrBuilder(
        int index) {
      if (platformsBuilder_ == null) {
        return platforms_.get(index);  } else {
        return platformsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public java.util.List<? extends io.notifyhub.v1.PlatformConfigOrBuilder> 
         getPlatformsOrBuilderList() {
      if (platformsBuilder_ != null) {
        return platformsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(platforms_);
      }
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public io.notifyhub.v1.PlatformConfig.Builder addPlatformsBuilder() {
      return internalGetPlatformsFieldBuilder().addBuilder(
          io.notifyhub.v1.PlatformConfig.getDefaultInstance());
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public io.notifyhub.v1.PlatformConfig.Builder addPlatformsBuilder(
        int index) {
      return internalGetPlatformsFieldBuilder().addBuilder(
          index, io.notifyhub.v1.PlatformConfig.getDefaultInstance());
    }
    /**
     * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
     */
    public java.util.List<io.notifyhub.v1.PlatformConfig.Builder> 
         getPlatformsBuilderList() {
      return internalGetPlatformsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        io.notifyhub.v1.PlatformConfig, io.notifyhub.v1.PlatformConfig.Builder, io.notifyhub.v1.PlatformConfigOrBuilder> 
        internalGetPlatformsFieldBuilder() {
      if (platformsBuilder_ == null) {
        platformsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            io.notifyhub.v1.PlatformConfig, io.notifyhub.v1.PlatformConfig.Builder, io.notifyhub.v1.PlatformConfigOrBuilder>(
                platforms_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        platforms_ = null;
      }
      return platformsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:notify.v1.PlatformList)
  }

  // @@protoc_insertion_point(class_scope:notify.v1.PlatformList)
  private static final io.notifyhub.v1.PlatformList DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.notifyhub.v1.PlatformList();
  }

  public static io.notifyhub.v1.PlatformList getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlatformList>
      PARSER = new com.google.protobuf.AbstractParser<PlatformList>() {
    @java.lang.Override
    public PlatformList parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlatformList> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlatformList> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.notifyhub.v1.PlatformList getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

