// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface PlatformRefOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.PlatformRef)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
