// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

/**
 * Protobuf type {@code notify.v1.PlatformConfig}
 */
@com.google.protobuf.Generated
public final class PlatformConfig extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notify.v1.PlatformConfig)
    PlatformConfigOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "PlatformConfig");
  }
  // Use PlatformConfig.newBuilder() to construct.
  private PlatformConfig(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PlatformConfig() {
    name_ = "";
    type_ = "";
    webhook_ = "";
    secret_ = "";
    topics_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    template_ = "";
    atMobiles_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 8:
        return internalGetExtra();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.notifyhub.v1.PlatformConfig.class, io.notifyhub.v1.PlatformConfig.Builder.class);
  }

  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object type_ = "";
  /**
   * <pre>
   * dingtalk | wecom | feishu | webhook
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  @java.lang.Override
  public java.lang.String getType() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      type_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * dingtalk | wecom | feishu | webhook
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTypeBytes() {
    java.lang.Object ref = type_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      type_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int WEBHOOK_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object webhook_ = "";
  /**
   * <code>string webhook = 3;</code>
   * @return The webhook.
   */
  @java.lang.Override
  public java.lang.String getWebhook() {
    java.lang.Object ref = webhook_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      webhook_ = s;
      return s;
    }
  }
  /**
   * <code>string webhook = 3;</code>
   * @return The bytes for webhook.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getWebhookBytes() {
    java.lang.Object ref = webhook_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      webhook_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SECRET_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private volatile java.lang.Object secret_ = "";
  /**
   * <code>string secret = 4;</code>
   * @return The secret.
   */
  @java.lang.Override
  public java.lang.String getSecret() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      secret_ = s;
      return s;
    }
  }
  /**
   * <code>string secret = 4;</code>
   * @return The bytes for secret.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getSecretBytes() {
    java.lang.Object ref = secret_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      secret_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOPICS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList topics_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @return A list containing the topics.
   */
  public com.google.protobuf.ProtocolStringList
      getTopicsList() {
    return topics_;
  }
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @return The count of topics.
   */
  public int getTopicsCount() {
    return topics_.size();
  }
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  public java.lang.String getTopics(int index) {
    return topics_.get(index);
  }
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  public com.google.protobuf.ByteString
      getTopicsBytes(int index) {
    return topics_.getByteString(index);
  }

  public static final int TEMPLATE_FIELD_NUMBER = 6;
  @SuppressWarnings("serial")
  private volatile java.lang.Object template_ = "";
  /**
   * <pre>
   * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
   * </pre>
   *
   * <code>string template = 6;</code>
   * @return The template.
   */
  @java.lang.Override
  public java.lang.String getTemplate() {
    java.lang.Object ref = template_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      template_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
   * </pre>
   *
   * <code>string template = 6;</code>
   * @return The bytes for template.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTemplateBytes() {
    java.lang.Object ref = template_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      template_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int AT_MOBILES_FIELD_NUMBER = 7;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList atMobiles_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @return A list containing the atMobiles.
   */
  public com.google.protobuf.ProtocolStringList
      getAtMobilesList() {
    return atMobiles_;
  }
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @return The count of atMobiles.
   */
  public int getAtMobilesCount() {
    return atMobiles_.size();
  }
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @param index The index of the element to return.
   * @return The atMobiles at the given index.
   */
  public java.lang.String getAtMobiles(int index) {
    return atMobiles_.get(index);
  }
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the atMobiles at the given index.
   */
  public com.google.protobuf.ByteString
      getAtMobilesBytes(int index) {
    return atMobiles_.getByteString(index);
  }

  public static final int EXTRA_FIELD_NUMBER = 8;
  private static final class ExtraDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_ExtraEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> extra_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetExtra() {
    if (extra_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ExtraDefaultEntryHolder.defaultEntry);
    }
    return extra_;
  }
  public int getExtraCount() {
    return internalGetExtra().getMap().size();
  }
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  @java.lang.Override
  public boolean containsExtra(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key, "map key");
    return internalGetExtra().getMap().containsKey(key);
  }
  /**
   * Use {@link #getExtraMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getExtra() {
    return getExtraMap();
  }
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getExtraMap() {
    return internalGetExtra().getMap();
  }
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getExtraOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    java.util.Objects.requireNonNull(key, "map key");
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtra().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  @java.lang.Override
  public java.lang.String getExtraOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key, "map key");
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetExtra().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int RETRY_FIELD_NUMBER = 9;
  private io.notifyhub.v1.RetryPolicy retry_;
  /**
   * <code>.notify.v1.RetryPolicy retry = 9;</code>
   * @return Whether the retry field is set.
   */
  @java.lang.Override
  public boolean hasRetry() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.notify.v1.RetryPolicy retry = 9;</code>
   * @return The retry.
   */
  @java.lang.Override
  public io.notifyhub.v1.RetryPolicy getRetry() {
    return retry_ == null ? io.notifyhub.v1.RetryPolicy.getDefaultInstance() : retry_;
  }
  /**
   * <code>.notify.v1.RetryPolicy retry = 9;</code>
   */
  @java.lang.Override
  public io.notifyhub.v1.RetryPolicyOrBuilder getRetryOrBuilder() {
    return retry_ == null ? io.notifyhub.v1.RetryPolicy.getDefaultInstance() : retry_;
  }

  public static final int RATE_LIMIT_QPS_FIELD_NUMBER = 10;
  private int rateLimitQps_ = 0;
  /**
   * <code>int32 rate_limit_qps = 10;</code>
   * @return The rateLimitQps.
   */
  @java.lang.Override
  public int getRateLimitQps() {
    return rateLimitQps_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(webhook_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, webhook_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(secret_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, secret_);
    }
    for (int i = 0; i < topics_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, topics_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(template_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 6, template_);
    }
    for (int i = 0; i < atMobiles_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 7, atMobiles_.getRaw(i));
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetExtra(),
        ExtraDefaultEntryHolder.defaultEntry,
        8);
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(9, getRetry());
    }
    if (rateLimitQps_ != 0) {
      output.writeInt32(10, rateLimitQps_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(name_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, name_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(type_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, type_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(webhook_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, webhook_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(secret_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(4, secret_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < topics_.size(); i++) {
        dataSize += computeStringSizeNoTag(topics_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTopicsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(template_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(6, template_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < atMobiles_.size(); i++) {
        dataSize += computeStringSizeNoTag(atMobiles_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getAtMobilesList().size();
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetExtra().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      extra__ = ExtraDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, extra__);
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, getRetry());
    }
    if (rateLimitQps_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(10, rateLimitQps_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.notifyhub.v1.PlatformConfig)) {
      return super.equals(obj);
    }
    io.notifyhub.v1.PlatformConfig other = (io.notifyhub.v1.PlatformConfig) obj;

    if (!getName()
        .equals(other.getName())) return false;
    if (!getType()
        .equals(other.getType())) return false;
    if (!getWebhook()
        .equals(other.getWebhook())) return false;
    if (!getSecret()
        .equals(other.getSecret())) return false;
    if (!getTopicsList()
        .equals(other.getTopicsList())) return false;
    if (!getTemplate()
        .equals(other.getTemplate())) return false;
    if (!getAtMobilesList()
        .equals(other.getAtMobilesList())) return false;
    if (!internalGetExtra().equals(
        other.internalGetExtra())) return false;
    if (hasRetry() != other.hasRetry()) return false;
    if (hasRetry()) {
      if (!getRetry()
          .equals(other.getRetry())) return false;
    }
    if (getRateLimitQps()
        != other.getRateLimitQps()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + getType().hashCode();
    hash = (37 * hash) + WEBHOOK_FIELD_NUMBER;
    hash = (53 * hash) + getWebhook().hashCode();
    hash = (37 * hash) + SECRET_FIELD_NUMBER;
    hash = (53 * hash) + getSecret().hashCode();
    if (getTopicsCount() > 0) {
      hash = (37 * hash) + TOPICS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicsList().hashCode();
    }
    hash = (37 * hash) + TEMPLATE_FIELD_NUMBER;
    hash = (53 * hash) + getTemplate().hashCode();
    if (getAtMobilesCount() > 0) {
      hash = (37 * hash) + AT_MOBILES_FIELD_NUMBER;
      hash = (53 * hash) + getAtMobilesList().hashCode();
    }
    if (!internalGetExtra().getMap().isEmpty()) {
      hash = (37 * hash) + EXTRA_FIELD_NUMBER;
      hash = (53 * hash) + internalGetExtra().hashCode();
    }
    if (hasRetry()) {
      hash = (37 * hash) + RETRY_FIELD_NUMBER;
      hash = (53 * hash) + getRetry().hashCode();
    }
    hash = (37 * hash) + RATE_LIMIT_QPS_FIELD_NUMBER;
    hash = (53 * hash) + getRateLimitQps();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.notifyhub.v1.PlatformConfig parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.notifyhub.v1.PlatformConfig parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.notifyhub.v1.PlatformConfig parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PlatformConfig parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.notifyhub.v1.PlatformConfig prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notify.v1.PlatformConfig}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notify.v1.PlatformConfig)
      io.notifyhub.v1.PlatformConfigOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 8:
          return internalGetExtra();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 8:
          return internalGetMutableExtra();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.notifyhub.v1.PlatformConfig.class, io.notifyhub.v1.PlatformConfig.Builder.class);
    }

    // Construct using io.notifyhub.v1.PlatformConfig.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetRetryFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      name_ = "";
      type_ = "";
      webhook_ = "";
      secret_ = "";
      topics_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      template_ = "";
      atMobiles_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      internalGetMutableExtra().clear();
      retry_ = null;
      if (retryBuilder_ != null) {
        retryBuilder_.dispose();
        retryBuilder_ = null;
      }
      rateLimitQps_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PlatformConfig_descriptor;
    }

    @java.lang.Override
    public io.notifyhub.v1.PlatformConfig getDefaultInstanceForType() {
      return io.notifyhub.v1.PlatformConfig.getDefaultInstance();
    }

    @java.lang.Override
    public io.notifyhub.v1.PlatformConfig build() {
      io.notifyhub.v1.PlatformConfig result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.notifyhub.v1.PlatformConfig buildPartial() {
      io.notifyhub.v1.PlatformConfig result = new io.notifyhub.v1.PlatformConfig(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.notifyhub.v1.PlatformConfig result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.name_ = name_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.type_ = type_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.webhook_ = webhook_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.secret_ = secret_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        topics_.makeImmutable();
        result.topics_ = topics_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.template_ = template_;
      }
      if (((from_bitField0_ & 0x00000040) != 0)) {
        atMobiles_.makeImmutable();
        result.atMobiles_ = atMobiles_;
      }
      if (((from_bitField0_ & 0x00000080) != 0)) {
        result.extra_ = internalGetExtra();
        result.extra_.makeImmutable();
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000100) != 0)) {
        result.retry_ = retryBuilder_ == null
            ? retry_
            : retryBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000200) != 0)) {
        result.rateLimitQps_ = rateLimitQps_;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.notifyhub.v1.PlatformConfig) {
        return mergeFrom((io.notifyhub.v1.PlatformConfig)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.notifyhub.v1.PlatformConfig other) {
      if (other == io.notifyhub.v1.PlatformConfig.getDefaultInstance()) return this;
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getType().isEmpty()) {
        type_ = other.type_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getWebhook().isEmpty()) {
        webhook_ = other.webhook_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (!other.getSecret().isEmpty()) {
        secret_ = other.secret_;
        bitField0_ |= 0x00000008;
        onChanged();
      }
      if (!other.topics_.isEmpty()) {
        if (topics_.isEmpty()) {
          topics_ = other.topics_;
          bitField0_ |= 0x00000010;
        } else {
          ensureTopicsIsMutable();
          topics_.addAll(other.topics_);
        }
        onChanged();
      }
      if (!other.getTemplate().isEmpty()) {
        template_ = other.template_;
        bitField0_ |= 0x00000020;
        onChanged();
      }
      if (!other.atMobiles_.isEmpty()) {
        if (atMobiles_.isEmpty()) {
          atMobiles_ = other.atMobiles_;
          bitField0_ |= 0x00000040;
        } else {
          ensureAtMobilesIsMutable();
          atMobiles_.addAll(other.atMobiles_);
        }
        onChanged();
      }
      internalGetMutableExtra().mergeFrom(
          other.internalGetExtra());
      bitField0_ |= 0x00000080;
      if (other.hasRetry()) {
        mergeRetry(other.getRetry());
      }
      if (other.getRateLimitQps() != 0) {
        setRateLimitQps(other.getRateLimitQps());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              type_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              webhook_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              secret_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              ensureTopicsIsMutable();
              topics_.add(input.readStringRequireUtf8());
              break;
            } // case 42
            case 50: {
              template_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            case 58: {
              ensureAtMobilesIsMutable();
              atMobiles_.add(input.readStringRequireUtf8());
              break;
            } // case 58
            case 66: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              extra__ = input.readMessage(
                  ExtraDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableExtra().getMutableMap().put(
                  extra__.getKey(), extra__.getValue());
              bitField0_ |= 0x00000080;
              break;
            } // case 66
            case 74: {
              input.readMessage(
                  internalGetRetryFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000100;
              break;
            } // case 74
            case 80: {
              rateLimitQps_ = input.readInt32();
              bitField0_ |= 0x00000200;
              break;
            } // case 80
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 1;</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object type_ = "";
    /**
     * <pre>
     * dingtalk | wecom | feishu | webhook
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The type.
     */
    public java.lang.String getType() {
      java.lang.Object ref = type_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        type_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * dingtalk | wecom | feishu | webhook
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return The bytes for type.
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      java.lang.Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * dingtalk | wecom | feishu | webhook
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The type to set.
     * @return This builder for chaining.
     */
    public Builder setType(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * dingtalk | wecom | feishu | webhook
     * </pre>
     *
     * <code>string type = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearType() {
      type_ = getDefaultInstance().getType();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * dingtalk | wecom | feishu | webhook
     * </pre>
     *
     * <code>string type = 2;</code>
     * @param value The bytes for type to set.
     * @return This builder for chaining.
     */
    public Builder setTypeBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      type_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object webhook_ = "";
    /**
     * <code>string webhook = 3;</code>
     * @return The webhook.
     */
    public java.lang.String getWebhook() {
      java.lang.Object ref = webhook_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        webhook_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string webhook = 3;</code>
     * @return The bytes for webhook.
     */
    public com.google.protobuf.ByteString
        getWebhookBytes() {
      java.lang.Object ref = webhook_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        webhook_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string webhook = 3;</code>
     * @param value The webhook to set.
     * @return This builder for chaining.
     */
    public Builder setWebhook(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      webhook_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string webhook = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearWebhook() {
      webhook_ = getDefaultInstance().getWebhook();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string webhook = 3;</code>
     * @param value The bytes for webhook to set.
     * @return This builder for chaining.
     */
    public Builder setWebhookBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      webhook_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private java.lang.Object secret_ = "";
    /**
     * <code>string secret = 4;</code>
     * @return The secret.
     */
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        secret_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string secret = 4;</code>
     * @return The bytes for secret.
     */
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string secret = 4;</code>
     * @param value The secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecret(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      secret_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>string secret = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearSecret() {
      secret_ = getDefaultInstance().getSecret();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    /**
     * <code>string secret = 4;</code>
     * @param value The bytes for secret to set.
     * @return This builder for chaining.
     */
    public Builder setSecretBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      secret_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList topics_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTopicsIsMutable() {
      if (!topics_.isModifiable()) {
        topics_ = new com.google.protobuf.LazyStringArrayList(topics_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @return A list containing the topics.
     */
    public com.google.protobuf.ProtocolStringList
        getTopicsList() {
      topics_.makeImmutable();
      return topics_;
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @return The count of topics.
     */
    public int getTopicsCount() {
      return topics_.size();
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @param index The index of the element to return.
     * @return The topics at the given index.
     */
    public java.lang.String getTopics(int index) {
      return topics_.get(index);
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the topics at the given index.
     */
    public com.google.protobuf.ByteString
        getTopicsBytes(int index) {
      return topics_.getByteString(index);
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @param index The index to set the value at.
     * @param value The topics to set.
     * @return This builder for chaining.
     */
    public Builder setTopics(
        int index, java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureTopicsIsMutable();
      topics_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @param value The topics to add.
     * @return This builder for chaining.
     */
    public Builder addTopics(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureTopicsIsMutable();
      topics_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @param values The topics to add.
     * @return This builder for chaining.
     */
    public Builder addAllTopics(
        java.lang.Iterable<java.lang.String> values) {
      ensureTopicsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, topics_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopics() {
      topics_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 路由规则，支持通配符
     * </pre>
     *
     * <code>repeated string topics = 5;</code>
     * @param value The bytes of the topics to add.
     * @return This builder for chaining.
     */
    public Builder addTopicsBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      ensureTopicsIsMutable();
      topics_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private java.lang.Object template_ = "";
    /**
     * <pre>
     * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
     * </pre>
     *
     * <code>string template = 6;</code>
     * @return The template.
     */
    public java.lang.String getTemplate() {
      java.lang.Object ref = template_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        template_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
     * </pre>
     *
     * <code>string template = 6;</code>
     * @return The bytes for template.
     */
    public com.google.protobuf.ByteString
        getTemplateBytes() {
      java.lang.Object ref = template_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        template_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
     * </pre>
     *
     * <code>string template = 6;</code>
     * @param value The template to set.
     * @return This builder for chaining.
     */
    public Builder setTemplate(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      template_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
     * </pre>
     *
     * <code>string template = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearTemplate() {
      template_ = getDefaultInstance().getTemplate();
      bitField0_ = (bitField0_ & ~0x00000020);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
     * </pre>
     *
     * <code>string template = 6;</code>
     * @param value The bytes for template to set.
     * @return This builder for chaining.
     */
    public Builder setTemplateBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      template_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList atMobiles_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureAtMobilesIsMutable() {
      if (!atMobiles_.isModifiable()) {
        atMobiles_ = new com.google.protobuf.LazyStringArrayList(atMobiles_);
      }
      bitField0_ |= 0x00000040;
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @return A list containing the atMobiles.
     */
    public com.google.protobuf.ProtocolStringList
        getAtMobilesList() {
      atMobiles_.makeImmutable();
      return atMobiles_;
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @return The count of atMobiles.
     */
    public int getAtMobilesCount() {
      return atMobiles_.size();
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @param index The index of the element to return.
     * @return The atMobiles at the given index.
     */
    public java.lang.String getAtMobiles(int index) {
      return atMobiles_.get(index);
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the atMobiles at the given index.
     */
    public com.google.protobuf.ByteString
        getAtMobilesBytes(int index) {
      return atMobiles_.getByteString(index);
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @param index The index to set the value at.
     * @param value The atMobiles to set.
     * @return This builder for chaining.
     */
    public Builder setAtMobiles(
        int index, java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureAtMobilesIsMutable();
      atMobiles_.set(index, value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @param value The atMobiles to add.
     * @return This builder for chaining.
     */
    public Builder addAtMobiles(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureAtMobilesIsMutable();
      atMobiles_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @param values The atMobiles to add.
     * @return This builder for chaining.
     */
    public Builder addAllAtMobiles(
        java.lang.Iterable<java.lang.String> values) {
      ensureAtMobilesIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, atMobiles_);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearAtMobiles() {
      atMobiles_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000040);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 钉钉 &#64; 手机号
     * </pre>
     *
     * <code>repeated string at_mobiles = 7;</code>
     * @param value The bytes of the atMobiles to add.
     * @return This builder for chaining.
     */
    public Builder addAtMobilesBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      ensureAtMobilesIsMutable();
      atMobiles_.add(value);
      bitField0_ |= 0x00000040;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> extra_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetExtra() {
      if (extra_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ExtraDefaultEntryHolder.defaultEntry);
      }
      return extra_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableExtra() {
      if (extra_ == null) {
        extra_ = com.google.protobuf.MapField.newMapField(
            ExtraDefaultEntryHolder.defaultEntry);
      }
      if (!extra_.isMutable()) {
        extra_ = extra_.copy();
      }
      bitField0_ |= 0x00000080;
      onChanged();
      return extra_;
    }
    public int getExtraCount() {
      return internalGetExtra().getMap().size();
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    @java.lang.Override
    public boolean containsExtra(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key, "map key");
      return internalGetExtra().getMap().containsKey(key);
    }
    /**
     * Use {@link #getExtraMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getExtra() {
      return getExtraMap();
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getExtraMap() {
      return internalGetExtra().getMap();
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getExtraOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.util.Objects.requireNonNull(key, "map key");
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtra().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    @java.lang.Override
    public java.lang.String getExtraOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key, "map key");
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetExtra().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearExtra() {
      bitField0_ = (bitField0_ & ~0x00000080);
      internalGetMutableExtra().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    public Builder removeExtra(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key, "map key");
      internalGetMutableExtra().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableExtra() {
      bitField0_ |= 0x00000080;
      return internalGetMutableExtra().getMutableMap();
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    public Builder putExtra(
        java.lang.String key,
        java.lang.String value) {
      java.util.Objects.requireNonNull(key, "map key");
      java.util.Objects.requireNonNull(value, "map value");
      internalGetMutableExtra().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000080;
      return this;
    }
    /**
     * <pre>
     * 扩展配置（如 webhook 渠道的 sign_header）
     * </pre>
     *
     * <code>map&lt;string, string&gt; extra = 8;</code>
     */
    public Builder putAllExtra(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableExtra().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000080;
      return this;
    }

    private io.notifyhub.v1.RetryPolicy retry_;
    private com.google.protobuf.SingleFieldBuilder<
        io.notifyhub.v1.RetryPolicy, io.notifyhub.v1.RetryPolicy.Builder, io.notifyhub.v1.RetryPolicyOrBuilder> retryBuilder_;
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     * @return Whether the retry field is set.
     */
    public boolean hasRetry() {
      return ((bitField0_ & 0x00000100) != 0);
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     * @return The retry.
     */
    public io.notifyhub.v1.RetryPolicy getRetry() {
      if (retryBuilder_ == null) {
        return retry_ == null ? io.notifyhub.v1.RetryPolicy.getDefaultInstance() : retry_;
      } else {
        return retryBuilder_.getMessage();
      }
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    public Builder setRetry(io.notifyhub.v1.RetryPolicy value) {
      if (retryBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        retry_ = value;
      } else {
        retryBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    public Builder setRetry(
        io.notifyhub.v1.RetryPolicy.Builder builderForValue) {
      if (retryBuilder_ == null) {
        retry_ = builderForValue.build();
      } else {
        retryBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000100;
      onChanged();
      return this;
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    public Builder mergeRetry(io.notifyhub.v1.RetryPolicy value) {
      if (retryBuilder_ == null) {
        if (((bitField0_ & 0x00000100) != 0) &&
          retry_ != null &&
          retry_ != io.notifyhub.v1.RetryPolicy.getDefaultInstance()) {
          getRetryBuilder().mergeFrom(value);
        } else {
          retry_ = value;
        }
      } else {
        retryBuilder_.mergeFrom(value);
      }
      if (retry_ != null) {
        bitField0_ |= 0x00000100;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    public Builder clearRetry() {
      bitField0_ = (bitField0_ & ~0x00000100);
      retry_ = null;
      if (retryBuilder_ != null) {
        retryBuilder_.dispose();
        retryBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    public io.notifyhub.v1.RetryPolicy.Builder getRetryBuilder() {
      bitField0_ |= 0x00000100;
      onChanged();
      return internalGetRetryFieldBuilder().getBuilder();
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    public io.notifyhub.v1.RetryPolicyOrBuilder getRetryOrBuilder() {
      if (retryBuilder_ != null) {
        return retryBuilder_.getMessageOrBuilder();
      } else {
        return retry_ == null ?
            io.notifyhub.v1.RetryPolicy.getDefaultInstance() : retry_;
      }
    }
    /**
     * <code>.notify.v1.RetryPolicy retry = 9;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.notifyhub.v1.RetryPolicy, io.notifyhub.v1.RetryPolicy.Builder, io.notifyhub.v1.RetryPolicyOrBuilder> 
        internalGetRetryFieldBuilder() {
      if (retryBuilder_ == null) {
        retryBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.notifyhub.v1.RetryPolicy, io.notifyhub.v1.RetryPolicy.Builder, io.notifyhub.v1.RetryPolicyOrBuilder>(
                getRetry(),
                getParentForChildren(),
                isClean());
        retry_ = null;
      }
      return retryBuilder_;
    }

    private int rateLimitQps_ ;
    /**
     * <code>int32 rate_limit_qps = 10;</code>
     * @return The rateLimitQps.
     */
    @java.lang.Override
    public int getRateLimitQps() {
      return rateLimitQps_;
    }
    /**
     * <code>int32 rate_limit_qps = 10;</code>
     * @param value The rateLimitQps to set.
     * @return This builder for chaining.
     */
    public Builder setRateLimitQps(int value) {

      rateLimitQps_ = value;
      bitField0_ |= 0x00000200;
      onChanged();
      return this;
    }
    /**
     * <code>int32 rate_limit_qps = 10;</code>
     * @return This builder for chaining.
     */
    public Builder clearRateLimitQps() {
      bitField0_ = (bitField0_ & ~0x00000200);
      rateLimitQps_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:notify.v1.PlatformConfig)
  }

  // @@protoc_insertion_point(class_scope:notify.v1.PlatformConfig)
  private static final io.notifyhub.v1.PlatformConfig DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.notifyhub.v1.PlatformConfig();
  }

  public static io.notifyhub.v1.PlatformConfig getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PlatformConfig>
      PARSER = new com.google.protobuf.AbstractParser<PlatformConfig>() {
    @java.lang.Override
    public PlatformConfig parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PlatformConfig> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PlatformConfig> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.notifyhub.v1.PlatformConfig getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

