// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface PlatformListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.PlatformList)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  java.util.List<io.notifyhub.v1.PlatformConfig> 
      getPlatformsList();
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  io.notifyhub.v1.PlatformConfig getPlatforms(int index);
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  int getPlatformsCount();
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  java.util.List<? extends io.notifyhub.v1.PlatformConfigOrBuilder> 
      getPlatformsOrBuilderList();
  /**
   * <code>repeated .notify.v1.PlatformConfig platforms = 1;</code>
   */
  io.notifyhub.v1.PlatformConfigOrBuilder getPlatformsOrBuilder(
      int index);
}
