// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface PlatformConfigOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.PlatformConfig)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * dingtalk | wecom | feishu | webhook
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <pre>
   * dingtalk | wecom | feishu | webhook
   * </pre>
   *
   * <code>string type = 2;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>string webhook = 3;</code>
   * @return The webhook.
   */
  java.lang.String getWebhook();
  /**
   * <code>string webhook = 3;</code>
   * @return The bytes for webhook.
   */
  com.google.protobuf.ByteString
      getWebhookBytes();

  /**
   * <code>string secret = 4;</code>
   * @return The secret.
   */
  java.lang.String getSecret();
  /**
   * <code>string secret = 4;</code>
   * @return The bytes for secret.
   */
  com.google.protobuf.ByteString
      getSecretBytes();

  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @return A list containing the topics.
   */
  java.util.List<java.lang.String>
      getTopicsList();
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @return The count of topics.
   */
  int getTopicsCount();
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  java.lang.String getTopics(int index);
  /**
   * <pre>
   * 路由规则，支持通配符
   * </pre>
   *
   * <code>repeated string topics = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  com.google.protobuf.ByteString
      getTopicsBytes(int index);

  /**
   * <pre>
   * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
   * </pre>
   *
   * <code>string template = 6;</code>
   * @return The template.
   */
  java.lang.String getTemplate();
  /**
   * <pre>
   * 渲染模板，占位符 {{title}} {{content}} {{params.xxx}}
   * </pre>
   *
   * <code>string template = 6;</code>
   * @return The bytes for template.
   */
  com.google.protobuf.ByteString
      getTemplateBytes();

  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @return A list containing the atMobiles.
   */
  java.util.List<java.lang.String>
      getAtMobilesList();
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @return The count of atMobiles.
   */
  int getAtMobilesCount();
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @param index The index of the element to return.
   * @return The atMobiles at the given index.
   */
  java.lang.String getAtMobiles(int index);
  /**
   * <pre>
   * 钉钉 &#64; 手机号
   * </pre>
   *
   * <code>repeated string at_mobiles = 7;</code>
   * @param index The index of the value to return.
   * @return The bytes of the atMobiles at the given index.
   */
  com.google.protobuf.ByteString
      getAtMobilesBytes(int index);

  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  int getExtraCount();
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  boolean containsExtra(
      java.lang.String key);
  /**
   * Use {@link #getExtraMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getExtra();
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getExtraMap();
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  /* nullable */
java.lang.String getExtraOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <pre>
   * 扩展配置（如 webhook 渠道的 sign_header）
   * </pre>
   *
   * <code>map&lt;string, string&gt; extra = 8;</code>
   */
  java.lang.String getExtraOrThrow(
      java.lang.String key);

  /**
   * <code>.notify.v1.RetryPolicy retry = 9;</code>
   * @return Whether the retry field is set.
   */
  boolean hasRetry();
  /**
   * <code>.notify.v1.RetryPolicy retry = 9;</code>
   * @return The retry.
   */
  io.notifyhub.v1.RetryPolicy getRetry();
  /**
   * <code>.notify.v1.RetryPolicy retry = 9;</code>
   */
  io.notifyhub.v1.RetryPolicyOrBuilder getRetryOrBuilder();

  /**
   * <code>int32 rate_limit_qps = 10;</code>
   * @return The rateLimitQps.
   */
  int getRateLimitQps();
}
