// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface PublishRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.PublishRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  java.lang.String getTopic();
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  com.google.protobuf.ByteString
      getTopicBytes();

  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  int getParamsCount();
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  boolean containsParams(
      java.lang.String key);
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getParams();
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getParamsMap();
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  /* nullable */
java.lang.String getParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  java.lang.String getParamsOrThrow(
      java.lang.String key);

  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @return A list containing the platforms.
   */
  java.util.List<java.lang.String>
      getPlatformsList();
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @return The count of platforms.
   */
  int getPlatformsCount();
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @param index The index of the element to return.
   * @return The platforms at the given index.
   */
  java.lang.String getPlatforms(int index);
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the platforms at the given index.
   */
  com.google.protobuf.ByteString
      getPlatformsBytes(int index);

  /**
   * <code>.notify.v1.Options options = 6;</code>
   * @return Whether the options field is set.
   */
  boolean hasOptions();
  /**
   * <code>.notify.v1.Options options = 6;</code>
   * @return The options.
   */
  io.notifyhub.v1.Options getOptions();
  /**
   * <code>.notify.v1.Options options = 6;</code>
   */
  io.notifyhub.v1.OptionsOrBuilder getOptionsOrBuilder();
}
