// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

/**
 * Protobuf type {@code notify.v1.PublishRequest}
 */
@com.google.protobuf.Generated
public final class PublishRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notify.v1.PublishRequest)
    PublishRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "PublishRequest");
  }
  // Use PublishRequest.newBuilder() to construct.
  private PublishRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublishRequest() {
    topic_ = "";
    title_ = "";
    content_ = "";
    platforms_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_descriptor;
  }

  @SuppressWarnings({"rawtypes"})
  @java.lang.Override
  protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
      int number) {
    switch (number) {
      case 4:
        return internalGetParams();
      default:
        throw new RuntimeException(
            "Invalid map field number: " + number);
    }
  }
  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.notifyhub.v1.PublishRequest.class, io.notifyhub.v1.PublishRequest.Builder.class);
  }

  private int bitField0_;
  public static final int TOPIC_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object topic_ = "";
  /**
   * <code>string topic = 1;</code>
   * @return The topic.
   */
  @java.lang.Override
  public java.lang.String getTopic() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      topic_ = s;
      return s;
    }
  }
  /**
   * <code>string topic = 1;</code>
   * @return The bytes for topic.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTopicBytes() {
    java.lang.Object ref = topic_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      topic_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TITLE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object title_ = "";
  /**
   * <code>string title = 2;</code>
   * @return The title.
   */
  @java.lang.Override
  public java.lang.String getTitle() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      title_ = s;
      return s;
    }
  }
  /**
   * <code>string title = 2;</code>
   * @return The bytes for title.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getTitleBytes() {
    java.lang.Object ref = title_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      title_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CONTENT_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object content_ = "";
  /**
   * <code>string content = 3;</code>
   * @return The content.
   */
  @java.lang.Override
  public java.lang.String getContent() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      content_ = s;
      return s;
    }
  }
  /**
   * <code>string content = 3;</code>
   * @return The bytes for content.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getContentBytes() {
    java.lang.Object ref = content_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      content_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PARAMS_FIELD_NUMBER = 4;
  private static final class ParamsDefaultEntryHolder {
    static final com.google.protobuf.MapEntry<
        java.lang.String, java.lang.String> defaultEntry =
            com.google.protobuf.MapEntry
            .<java.lang.String, java.lang.String>newDefaultInstance(
                io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_ParamsEntry_descriptor, 
                com.google.protobuf.WireFormat.FieldType.STRING,
                "",
                com.google.protobuf.WireFormat.FieldType.STRING,
                "");
  }
  @SuppressWarnings("serial")
  private com.google.protobuf.MapField<
      java.lang.String, java.lang.String> params_;
  private com.google.protobuf.MapField<java.lang.String, java.lang.String>
  internalGetParams() {
    if (params_ == null) {
      return com.google.protobuf.MapField.emptyMapField(
          ParamsDefaultEntryHolder.defaultEntry);
    }
    return params_;
  }
  public int getParamsCount() {
    return internalGetParams().getMap().size();
  }
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  @java.lang.Override
  public boolean containsParams(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key, "map key");
    return internalGetParams().getMap().containsKey(key);
  }
  /**
   * Use {@link #getParamsMap()} instead.
   */
  @java.lang.Override
  @java.lang.Deprecated
  public java.util.Map<java.lang.String, java.lang.String> getParams() {
    return getParamsMap();
  }
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  @java.lang.Override
  public java.util.Map<java.lang.String, java.lang.String> getParamsMap() {
    return internalGetParams().getMap();
  }
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  @java.lang.Override
  public /* nullable */
java.lang.String getParamsOrDefault(
      java.lang.String key,
      /* nullable */
java.lang.String defaultValue) {
    java.util.Objects.requireNonNull(key, "map key");
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetParams().getMap();
    return map.containsKey(key) ? map.get(key) : defaultValue;
  }
  /**
   * <code>map&lt;string, string&gt; params = 4;</code>
   */
  @java.lang.Override
  public java.lang.String getParamsOrThrow(
      java.lang.String key) {
    java.util.Objects.requireNonNull(key, "map key");
    java.util.Map<java.lang.String, java.lang.String> map =
        internalGetParams().getMap();
    if (!map.containsKey(key)) {
      throw new java.lang.IllegalArgumentException();
    }
    return map.get(key);
  }

  public static final int PLATFORMS_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList platforms_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @return A list containing the platforms.
   */
  public com.google.protobuf.ProtocolStringList
      getPlatformsList() {
    return platforms_;
  }
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @return The count of platforms.
   */
  public int getPlatformsCount() {
    return platforms_.size();
  }
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @param index The index of the element to return.
   * @return The platforms at the given index.
   */
  public java.lang.String getPlatforms(int index) {
    return platforms_.get(index);
  }
  /**
   * <pre>
   * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
   * </pre>
   *
   * <code>repeated string platforms = 5;</code>
   * @param index The index of the value to return.
   * @return The bytes of the platforms at the given index.
   */
  public com.google.protobuf.ByteString
      getPlatformsBytes(int index) {
    return platforms_.getByteString(index);
  }

  public static final int OPTIONS_FIELD_NUMBER = 6;
  private io.notifyhub.v1.Options options_;
  /**
   * <code>.notify.v1.Options options = 6;</code>
   * @return Whether the options field is set.
   */
  @java.lang.Override
  public boolean hasOptions() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.notify.v1.Options options = 6;</code>
   * @return The options.
   */
  @java.lang.Override
  public io.notifyhub.v1.Options getOptions() {
    return options_ == null ? io.notifyhub.v1.Options.getDefaultInstance() : options_;
  }
  /**
   * <code>.notify.v1.Options options = 6;</code>
   */
  @java.lang.Override
  public io.notifyhub.v1.OptionsOrBuilder getOptionsOrBuilder() {
    return options_ == null ? io.notifyhub.v1.Options.getDefaultInstance() : options_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(topic_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, topic_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, content_);
    }
    com.google.protobuf.GeneratedMessage
      .serializeStringMapTo(
        output,
        internalGetParams(),
        ParamsDefaultEntryHolder.defaultEntry,
        4);
    for (int i = 0; i < platforms_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, platforms_.getRaw(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(6, getOptions());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(topic_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, topic_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(title_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, title_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(content_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, content_);
    }
    for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
         : internalGetParams().getMap().entrySet()) {
      com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
      params__ = ParamsDefaultEntryHolder.defaultEntry.newBuilderForType()
          .setKey(entry.getKey())
          .setValue(entry.getValue())
          .buildPartial();
      size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, params__);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < platforms_.size(); i++) {
        dataSize += computeStringSizeNoTag(platforms_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getPlatformsList().size();
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, getOptions());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.notifyhub.v1.PublishRequest)) {
      return super.equals(obj);
    }
    io.notifyhub.v1.PublishRequest other = (io.notifyhub.v1.PublishRequest) obj;

    if (!getTopic()
        .equals(other.getTopic())) return false;
    if (!getTitle()
        .equals(other.getTitle())) return false;
    if (!getContent()
        .equals(other.getContent())) return false;
    if (!internalGetParams().equals(
        other.internalGetParams())) return false;
    if (!getPlatformsList()
        .equals(other.getPlatformsList())) return false;
    if (hasOptions() != other.hasOptions()) return false;
    if (hasOptions()) {
      if (!getOptions()
          .equals(other.getOptions())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TOPIC_FIELD_NUMBER;
    hash = (53 * hash) + getTopic().hashCode();
    hash = (37 * hash) + TITLE_FIELD_NUMBER;
    hash = (53 * hash) + getTitle().hashCode();
    hash = (37 * hash) + CONTENT_FIELD_NUMBER;
    hash = (53 * hash) + getContent().hashCode();
    if (!internalGetParams().getMap().isEmpty()) {
      hash = (37 * hash) + PARAMS_FIELD_NUMBER;
      hash = (53 * hash) + internalGetParams().hashCode();
    }
    if (getPlatformsCount() > 0) {
      hash = (37 * hash) + PLATFORMS_FIELD_NUMBER;
      hash = (53 * hash) + getPlatformsList().hashCode();
    }
    if (hasOptions()) {
      hash = (37 * hash) + OPTIONS_FIELD_NUMBER;
      hash = (53 * hash) + getOptions().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.notifyhub.v1.PublishRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.notifyhub.v1.PublishRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.notifyhub.v1.PublishRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PublishRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.notifyhub.v1.PublishRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notify.v1.PublishRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notify.v1.PublishRequest)
      io.notifyhub.v1.PublishRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapFieldReflectionAccessor internalGetMutableMapFieldReflection(
        int number) {
      switch (number) {
        case 4:
          return internalGetMutableParams();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.notifyhub.v1.PublishRequest.class, io.notifyhub.v1.PublishRequest.Builder.class);
    }

    // Construct using io.notifyhub.v1.PublishRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetOptionsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topic_ = "";
      title_ = "";
      content_ = "";
      internalGetMutableParams().clear();
      platforms_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      options_ = null;
      if (optionsBuilder_ != null) {
        optionsBuilder_.dispose();
        optionsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishRequest_descriptor;
    }

    @java.lang.Override
    public io.notifyhub.v1.PublishRequest getDefaultInstanceForType() {
      return io.notifyhub.v1.PublishRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.notifyhub.v1.PublishRequest build() {
      io.notifyhub.v1.PublishRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.notifyhub.v1.PublishRequest buildPartial() {
      io.notifyhub.v1.PublishRequest result = new io.notifyhub.v1.PublishRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.notifyhub.v1.PublishRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.topic_ = topic_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.title_ = title_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.content_ = content_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.params_ = internalGetParams();
        result.params_.makeImmutable();
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        platforms_.makeImmutable();
        result.platforms_ = platforms_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.options_ = optionsBuilder_ == null
            ? options_
            : optionsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.notifyhub.v1.PublishRequest) {
        return mergeFrom((io.notifyhub.v1.PublishRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.notifyhub.v1.PublishRequest other) {
      if (other == io.notifyhub.v1.PublishRequest.getDefaultInstance()) return this;
      if (!other.getTopic().isEmpty()) {
        topic_ = other.topic_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (!other.getTitle().isEmpty()) {
        title_ = other.title_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (!other.getContent().isEmpty()) {
        content_ = other.content_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      internalGetMutableParams().mergeFrom(
          other.internalGetParams());
      bitField0_ |= 0x00000008;
      if (!other.platforms_.isEmpty()) {
        if (platforms_.isEmpty()) {
          platforms_ = other.platforms_;
          bitField0_ |= 0x00000010;
        } else {
          ensurePlatformsIsMutable();
          platforms_.addAll(other.platforms_);
        }
        onChanged();
      }
      if (other.hasOptions()) {
        mergeOptions(other.getOptions());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              topic_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              title_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              content_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 34: {
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              params__ = input.readMessage(
                  ParamsDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              internalGetMutableParams().getMutableMap().put(
                  params__.getKey(), params__.getValue());
              bitField0_ |= 0x00000008;
              break;
            } // case 34
            case 42: {
              ensurePlatformsIsMutable();
              platforms_.add(input.readStringRequireUtf8());
              break;
            } // case 42
            case 50: {
              input.readMessage(
                  internalGetOptionsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000020;
              break;
            } // case 50
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object topic_ = "";
    /**
     * <code>string topic = 1;</code>
     * @return The topic.
     */
    public java.lang.String getTopic() {
      java.lang.Object ref = topic_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        topic_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @return The bytes for topic.
     */
    public com.google.protobuf.ByteString
        getTopicBytes() {
      java.lang.Object ref = topic_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        topic_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopic(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      topic_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopic() {
      topic_ = getDefaultInstance().getTopic();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string topic = 1;</code>
     * @param value The bytes for topic to set.
     * @return This builder for chaining.
     */
    public Builder setTopicBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      topic_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object title_ = "";
    /**
     * <code>string title = 2;</code>
     * @return The title.
     */
    public java.lang.String getTitle() {
      java.lang.Object ref = title_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        title_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @return The bytes for title.
     */
    public com.google.protobuf.ByteString
        getTitleBytes() {
      java.lang.Object ref = title_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        title_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string title = 2;</code>
     * @param value The title to set.
     * @return This builder for chaining.
     */
    public Builder setTitle(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearTitle() {
      title_ = getDefaultInstance().getTitle();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string title = 2;</code>
     * @param value The bytes for title to set.
     * @return This builder for chaining.
     */
    public Builder setTitleBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      title_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object content_ = "";
    /**
     * <code>string content = 3;</code>
     * @return The content.
     */
    public java.lang.String getContent() {
      java.lang.Object ref = content_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        content_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @return The bytes for content.
     */
    public com.google.protobuf.ByteString
        getContentBytes() {
      java.lang.Object ref = content_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        content_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string content = 3;</code>
     * @param value The content to set.
     * @return This builder for chaining.
     */
    public Builder setContent(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      content_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearContent() {
      content_ = getDefaultInstance().getContent();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string content = 3;</code>
     * @param value The bytes for content to set.
     * @return This builder for chaining.
     */
    public Builder setContentBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      content_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> params_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetParams() {
      if (params_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      return params_;
    }
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
        internalGetMutableParams() {
      if (params_ == null) {
        params_ = com.google.protobuf.MapField.newMapField(
            ParamsDefaultEntryHolder.defaultEntry);
      }
      if (!params_.isMutable()) {
        params_ = params_.copy();
      }
      bitField0_ |= 0x00000008;
      onChanged();
      return params_;
    }
    public int getParamsCount() {
      return internalGetParams().getMap().size();
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    @java.lang.Override
    public boolean containsParams(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key, "map key");
      return internalGetParams().getMap().containsKey(key);
    }
    /**
     * Use {@link #getParamsMap()} instead.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String> getParams() {
      return getParamsMap();
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    @java.lang.Override
    public java.util.Map<java.lang.String, java.lang.String> getParamsMap() {
      return internalGetParams().getMap();
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    @java.lang.Override
    public /* nullable */
java.lang.String getParamsOrDefault(
        java.lang.String key,
        /* nullable */
java.lang.String defaultValue) {
      java.util.Objects.requireNonNull(key, "map key");
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParams().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    @java.lang.Override
    public java.lang.String getParamsOrThrow(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key, "map key");
      java.util.Map<java.lang.String, java.lang.String> map =
          internalGetParams().getMap();
      if (!map.containsKey(key)) {
        throw new java.lang.IllegalArgumentException();
      }
      return map.get(key);
    }
    public Builder clearParams() {
      bitField0_ = (bitField0_ & ~0x00000008);
      internalGetMutableParams().getMutableMap()
          .clear();
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    public Builder removeParams(
        java.lang.String key) {
      java.util.Objects.requireNonNull(key, "map key");
      internalGetMutableParams().getMutableMap()
          .remove(key);
      return this;
    }
    /**
     * Use alternate mutation accessors instead.
     */
    @java.lang.Deprecated
    public java.util.Map<java.lang.String, java.lang.String>
        getMutableParams() {
      bitField0_ |= 0x00000008;
      return internalGetMutableParams().getMutableMap();
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    public Builder putParams(
        java.lang.String key,
        java.lang.String value) {
      java.util.Objects.requireNonNull(key, "map key");
      java.util.Objects.requireNonNull(value, "map value");
      internalGetMutableParams().getMutableMap()
          .put(key, value);
      bitField0_ |= 0x00000008;
      return this;
    }
    /**
     * <code>map&lt;string, string&gt; params = 4;</code>
     */
    public Builder putAllParams(
        java.util.Map<java.lang.String, java.lang.String> values) {
      internalGetMutableParams().getMutableMap()
          .putAll(values);
      bitField0_ |= 0x00000008;
      return this;
    }

    private com.google.protobuf.LazyStringArrayList platforms_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensurePlatformsIsMutable() {
      if (!platforms_.isModifiable()) {
        platforms_ = new com.google.protobuf.LazyStringArrayList(platforms_);
      }
      bitField0_ |= 0x00000010;
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @return A list containing the platforms.
     */
    public com.google.protobuf.ProtocolStringList
        getPlatformsList() {
      platforms_.makeImmutable();
      return platforms_;
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @return The count of platforms.
     */
    public int getPlatformsCount() {
      return platforms_.size();
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @param index The index of the element to return.
     * @return The platforms at the given index.
     */
    public java.lang.String getPlatforms(int index) {
      return platforms_.get(index);
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the platforms at the given index.
     */
    public com.google.protobuf.ByteString
        getPlatformsBytes(int index) {
      return platforms_.getByteString(index);
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @param index The index to set the value at.
     * @param value The platforms to set.
     * @return This builder for chaining.
     */
    public Builder setPlatforms(
        int index, java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensurePlatformsIsMutable();
      platforms_.set(index, value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @param value The platforms to add.
     * @return This builder for chaining.
     */
    public Builder addPlatforms(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensurePlatformsIsMutable();
      platforms_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @param values The platforms to add.
     * @return This builder for chaining.
     */
    public Builder addAllPlatforms(
        java.lang.Iterable<java.lang.String> values) {
      ensurePlatformsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, platforms_);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearPlatforms() {
      platforms_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 显式指定目标平台名（覆盖按 topic 的路由规则；平台不存在返回 NOT_FOUND）。
     * </pre>
     *
     * <code>repeated string platforms = 5;</code>
     * @param value The bytes of the platforms to add.
     * @return This builder for chaining.
     */
    public Builder addPlatformsBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      ensurePlatformsIsMutable();
      platforms_.add(value);
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    private io.notifyhub.v1.Options options_;
    private com.google.protobuf.SingleFieldBuilder<
        io.notifyhub.v1.Options, io.notifyhub.v1.Options.Builder, io.notifyhub.v1.OptionsOrBuilder> optionsBuilder_;
    /**
     * <code>.notify.v1.Options options = 6;</code>
     * @return Whether the options field is set.
     */
    public boolean hasOptions() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     * @return The options.
     */
    public io.notifyhub.v1.Options getOptions() {
      if (optionsBuilder_ == null) {
        return options_ == null ? io.notifyhub.v1.Options.getDefaultInstance() : options_;
      } else {
        return optionsBuilder_.getMessage();
      }
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    public Builder setOptions(io.notifyhub.v1.Options value) {
      if (optionsBuilder_ == null) {
        java.util.Objects.requireNonNull(value);
        options_ = value;
      } else {
        optionsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    public Builder setOptions(
        io.notifyhub.v1.Options.Builder builderForValue) {
      if (optionsBuilder_ == null) {
        options_ = builderForValue.build();
      } else {
        optionsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    public Builder mergeOptions(io.notifyhub.v1.Options value) {
      if (optionsBuilder_ == null) {
        if (((bitField0_ & 0x00000020) != 0) &&
          options_ != null &&
          options_ != io.notifyhub.v1.Options.getDefaultInstance()) {
          getOptionsBuilder().mergeFrom(value);
        } else {
          options_ = value;
        }
      } else {
        optionsBuilder_.mergeFrom(value);
      }
      if (options_ != null) {
        bitField0_ |= 0x00000020;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    public Builder clearOptions() {
      bitField0_ = (bitField0_ & ~0x00000020);
      options_ = null;
      if (optionsBuilder_ != null) {
        optionsBuilder_.dispose();
        optionsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    public io.notifyhub.v1.Options.Builder getOptionsBuilder() {
      bitField0_ |= 0x00000020;
      onChanged();
      return internalGetOptionsFieldBuilder().getBuilder();
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    public io.notifyhub.v1.OptionsOrBuilder getOptionsOrBuilder() {
      if (optionsBuilder_ != null) {
        return optionsBuilder_.getMessageOrBuilder();
      } else {
        return options_ == null ?
            io.notifyhub.v1.Options.getDefaultInstance() : options_;
      }
    }
    /**
     * <code>.notify.v1.Options options = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        io.notifyhub.v1.Options, io.notifyhub.v1.Options.Builder, io.notifyhub.v1.OptionsOrBuilder> 
        internalGetOptionsFieldBuilder() {
      if (optionsBuilder_ == null) {
        optionsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            io.notifyhub.v1.Options, io.notifyhub.v1.Options.Builder, io.notifyhub.v1.OptionsOrBuilder>(
                getOptions(),
                getParentForChildren(),
                isClean());
        options_ = null;
      }
      return optionsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:notify.v1.PublishRequest)
  }

  // @@protoc_insertion_point(class_scope:notify.v1.PublishRequest)
  private static final io.notifyhub.v1.PublishRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.notifyhub.v1.PublishRequest();
  }

  public static io.notifyhub.v1.PublishRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishRequest>
      PARSER = new com.google.protobuf.AbstractParser<PublishRequest>() {
    @java.lang.Override
    public PublishRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublishRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublishRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.notifyhub.v1.PublishRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

