// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

/**
 * Protobuf type {@code notify.v1.PublishAck}
 */
@com.google.protobuf.Generated
public final class PublishAck extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notify.v1.PublishAck)
    PublishAckOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "PublishAck");
  }
  // Use PublishAck.newBuilder() to construct.
  private PublishAck(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PublishAck() {
    eventId_ = "";
    matchedPlatforms_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    error_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishAck_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishAck_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishAck_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.notifyhub.v1.PublishAck.class, io.notifyhub.v1.PublishAck.Builder.class);
  }

  public static final int EVENT_ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object eventId_ = "";
  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  @java.lang.Override
  public java.lang.String getEventId() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      eventId_ = s;
      return s;
    }
  }
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getEventIdBytes() {
    java.lang.Object ref = eventId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      eventId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ACCEPTED_FIELD_NUMBER = 2;
  private boolean accepted_ = false;
  /**
   * <code>bool accepted = 2;</code>
   * @return The accepted.
   */
  @java.lang.Override
  public boolean getAccepted() {
    return accepted_;
  }

  public static final int DEDUPLICATED_FIELD_NUMBER = 3;
  private boolean deduplicated_ = false;
  /**
   * <code>bool deduplicated = 3;</code>
   * @return The deduplicated.
   */
  @java.lang.Override
  public boolean getDeduplicated() {
    return deduplicated_;
  }

  public static final int MATCHED_PLATFORMS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList matchedPlatforms_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @return A list containing the matchedPlatforms.
   */
  public com.google.protobuf.ProtocolStringList
      getMatchedPlatformsList() {
    return matchedPlatforms_;
  }
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @return The count of matchedPlatforms.
   */
  public int getMatchedPlatformsCount() {
    return matchedPlatforms_.size();
  }
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @param index The index of the element to return.
   * @return The matchedPlatforms at the given index.
   */
  public java.lang.String getMatchedPlatforms(int index) {
    return matchedPlatforms_.get(index);
  }
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the matchedPlatforms at the given index.
   */
  public com.google.protobuf.ByteString
      getMatchedPlatformsBytes(int index) {
    return matchedPlatforms_.getByteString(index);
  }

  public static final int ERROR_FIELD_NUMBER = 5;
  @SuppressWarnings("serial")
  private volatile java.lang.Object error_ = "";
  /**
   * <pre>
   * accepted=false 时的原因（批量流中按条返回，不中断流）。
   * </pre>
   *
   * <code>string error = 5;</code>
   * @return The error.
   */
  @java.lang.Override
  public java.lang.String getError() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      error_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * accepted=false 时的原因（批量流中按条返回，不中断流）。
   * </pre>
   *
   * <code>string error = 5;</code>
   * @return The bytes for error.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getErrorBytes() {
    java.lang.Object ref = error_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      error_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, eventId_);
    }
    if (accepted_ != false) {
      output.writeBool(2, accepted_);
    }
    if (deduplicated_ != false) {
      output.writeBool(3, deduplicated_);
    }
    for (int i = 0; i < matchedPlatforms_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 4, matchedPlatforms_.getRaw(i));
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 5, error_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(eventId_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, eventId_);
    }
    if (accepted_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(2, accepted_);
    }
    if (deduplicated_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(3, deduplicated_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < matchedPlatforms_.size(); i++) {
        dataSize += computeStringSizeNoTag(matchedPlatforms_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getMatchedPlatformsList().size();
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(error_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(5, error_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.notifyhub.v1.PublishAck)) {
      return super.equals(obj);
    }
    io.notifyhub.v1.PublishAck other = (io.notifyhub.v1.PublishAck) obj;

    if (!getEventId()
        .equals(other.getEventId())) return false;
    if (getAccepted()
        != other.getAccepted()) return false;
    if (getDeduplicated()
        != other.getDeduplicated()) return false;
    if (!getMatchedPlatformsList()
        .equals(other.getMatchedPlatformsList())) return false;
    if (!getError()
        .equals(other.getError())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EVENT_ID_FIELD_NUMBER;
    hash = (53 * hash) + getEventId().hashCode();
    hash = (37 * hash) + ACCEPTED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getAccepted());
    hash = (37 * hash) + DEDUPLICATED_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getDeduplicated());
    if (getMatchedPlatformsCount() > 0) {
      hash = (37 * hash) + MATCHED_PLATFORMS_FIELD_NUMBER;
      hash = (53 * hash) + getMatchedPlatformsList().hashCode();
    }
    hash = (37 * hash) + ERROR_FIELD_NUMBER;
    hash = (53 * hash) + getError().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.notifyhub.v1.PublishAck parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.notifyhub.v1.PublishAck parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.notifyhub.v1.PublishAck parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.PublishAck parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.notifyhub.v1.PublishAck prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notify.v1.PublishAck}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notify.v1.PublishAck)
      io.notifyhub.v1.PublishAckOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishAck_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishAck_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.notifyhub.v1.PublishAck.class, io.notifyhub.v1.PublishAck.Builder.class);
    }

    // Construct using io.notifyhub.v1.PublishAck.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      eventId_ = "";
      accepted_ = false;
      deduplicated_ = false;
      matchedPlatforms_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      error_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_PublishAck_descriptor;
    }

    @java.lang.Override
    public io.notifyhub.v1.PublishAck getDefaultInstanceForType() {
      return io.notifyhub.v1.PublishAck.getDefaultInstance();
    }

    @java.lang.Override
    public io.notifyhub.v1.PublishAck build() {
      io.notifyhub.v1.PublishAck result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.notifyhub.v1.PublishAck buildPartial() {
      io.notifyhub.v1.PublishAck result = new io.notifyhub.v1.PublishAck(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.notifyhub.v1.PublishAck result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.eventId_ = eventId_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.accepted_ = accepted_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.deduplicated_ = deduplicated_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        matchedPlatforms_.makeImmutable();
        result.matchedPlatforms_ = matchedPlatforms_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.error_ = error_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.notifyhub.v1.PublishAck) {
        return mergeFrom((io.notifyhub.v1.PublishAck)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.notifyhub.v1.PublishAck other) {
      if (other == io.notifyhub.v1.PublishAck.getDefaultInstance()) return this;
      if (!other.getEventId().isEmpty()) {
        eventId_ = other.eventId_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.getAccepted() != false) {
        setAccepted(other.getAccepted());
      }
      if (other.getDeduplicated() != false) {
        setDeduplicated(other.getDeduplicated());
      }
      if (!other.matchedPlatforms_.isEmpty()) {
        if (matchedPlatforms_.isEmpty()) {
          matchedPlatforms_ = other.matchedPlatforms_;
          bitField0_ |= 0x00000008;
        } else {
          ensureMatchedPlatformsIsMutable();
          matchedPlatforms_.addAll(other.matchedPlatforms_);
        }
        onChanged();
      }
      if (!other.getError().isEmpty()) {
        error_ = other.error_;
        bitField0_ |= 0x00000010;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              eventId_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              accepted_ = input.readBool();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              deduplicated_ = input.readBool();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 34: {
              ensureMatchedPlatformsIsMutable();
              matchedPlatforms_.add(input.readStringRequireUtf8());
              break;
            } // case 34
            case 42: {
              error_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object eventId_ = "";
    /**
     * <code>string event_id = 1;</code>
     * @return The eventId.
     */
    public java.lang.String getEventId() {
      java.lang.Object ref = eventId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        eventId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @return The bytes for eventId.
     */
    public com.google.protobuf.ByteString
        getEventIdBytes() {
      java.lang.Object ref = eventId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        eventId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventId(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearEventId() {
      eventId_ = getDefaultInstance().getEventId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string event_id = 1;</code>
     * @param value The bytes for eventId to set.
     * @return This builder for chaining.
     */
    public Builder setEventIdBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      eventId_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private boolean accepted_ ;
    /**
     * <code>bool accepted = 2;</code>
     * @return The accepted.
     */
    @java.lang.Override
    public boolean getAccepted() {
      return accepted_;
    }
    /**
     * <code>bool accepted = 2;</code>
     * @param value The accepted to set.
     * @return This builder for chaining.
     */
    public Builder setAccepted(boolean value) {

      accepted_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>bool accepted = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAccepted() {
      bitField0_ = (bitField0_ & ~0x00000002);
      accepted_ = false;
      onChanged();
      return this;
    }

    private boolean deduplicated_ ;
    /**
     * <code>bool deduplicated = 3;</code>
     * @return The deduplicated.
     */
    @java.lang.Override
    public boolean getDeduplicated() {
      return deduplicated_;
    }
    /**
     * <code>bool deduplicated = 3;</code>
     * @param value The deduplicated to set.
     * @return This builder for chaining.
     */
    public Builder setDeduplicated(boolean value) {

      deduplicated_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>bool deduplicated = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearDeduplicated() {
      bitField0_ = (bitField0_ & ~0x00000004);
      deduplicated_ = false;
      onChanged();
      return this;
    }

    private com.google.protobuf.LazyStringArrayList matchedPlatforms_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureMatchedPlatformsIsMutable() {
      if (!matchedPlatforms_.isModifiable()) {
        matchedPlatforms_ = new com.google.protobuf.LazyStringArrayList(matchedPlatforms_);
      }
      bitField0_ |= 0x00000008;
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @return A list containing the matchedPlatforms.
     */
    public com.google.protobuf.ProtocolStringList
        getMatchedPlatformsList() {
      matchedPlatforms_.makeImmutable();
      return matchedPlatforms_;
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @return The count of matchedPlatforms.
     */
    public int getMatchedPlatformsCount() {
      return matchedPlatforms_.size();
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @param index The index of the element to return.
     * @return The matchedPlatforms at the given index.
     */
    public java.lang.String getMatchedPlatforms(int index) {
      return matchedPlatforms_.get(index);
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @param index The index of the value to return.
     * @return The bytes of the matchedPlatforms at the given index.
     */
    public com.google.protobuf.ByteString
        getMatchedPlatformsBytes(int index) {
      return matchedPlatforms_.getByteString(index);
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @param index The index to set the value at.
     * @param value The matchedPlatforms to set.
     * @return This builder for chaining.
     */
    public Builder setMatchedPlatforms(
        int index, java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureMatchedPlatformsIsMutable();
      matchedPlatforms_.set(index, value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @param value The matchedPlatforms to add.
     * @return This builder for chaining.
     */
    public Builder addMatchedPlatforms(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureMatchedPlatformsIsMutable();
      matchedPlatforms_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @param values The matchedPlatforms to add.
     * @return This builder for chaining.
     */
    public Builder addAllMatchedPlatforms(
        java.lang.Iterable<java.lang.String> values) {
      ensureMatchedPlatformsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, matchedPlatforms_);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMatchedPlatforms() {
      matchedPlatforms_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);;
      onChanged();
      return this;
    }
    /**
     * <code>repeated string matched_platforms = 4;</code>
     * @param value The bytes of the matchedPlatforms to add.
     * @return This builder for chaining.
     */
    public Builder addMatchedPlatformsBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      ensureMatchedPlatformsIsMutable();
      matchedPlatforms_.add(value);
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }

    private java.lang.Object error_ = "";
    /**
     * <pre>
     * accepted=false 时的原因（批量流中按条返回，不中断流）。
     * </pre>
     *
     * <code>string error = 5;</code>
     * @return The error.
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        error_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * accepted=false 时的原因（批量流中按条返回，不中断流）。
     * </pre>
     *
     * <code>string error = 5;</code>
     * @return The bytes for error.
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * accepted=false 时的原因（批量流中按条返回，不中断流）。
     * </pre>
     *
     * <code>string error = 5;</code>
     * @param value The error to set.
     * @return This builder for chaining.
     */
    public Builder setError(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      error_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * accepted=false 时的原因（批量流中按条返回，不中断流）。
     * </pre>
     *
     * <code>string error = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearError() {
      error_ = getDefaultInstance().getError();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    /**
     * <pre>
     * accepted=false 时的原因（批量流中按条返回，不中断流）。
     * </pre>
     *
     * <code>string error = 5;</code>
     * @param value The bytes for error to set.
     * @return This builder for chaining.
     */
    public Builder setErrorBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      error_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:notify.v1.PublishAck)
  }

  // @@protoc_insertion_point(class_scope:notify.v1.PublishAck)
  private static final io.notifyhub.v1.PublishAck DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.notifyhub.v1.PublishAck();
  }

  public static io.notifyhub.v1.PublishAck getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PublishAck>
      PARSER = new com.google.protobuf.AbstractParser<PublishAck>() {
    @java.lang.Override
    public PublishAck parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PublishAck> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PublishAck> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.notifyhub.v1.PublishAck getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

