// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface PublishAckOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.PublishAck)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string event_id = 1;</code>
   * @return The eventId.
   */
  java.lang.String getEventId();
  /**
   * <code>string event_id = 1;</code>
   * @return The bytes for eventId.
   */
  com.google.protobuf.ByteString
      getEventIdBytes();

  /**
   * <code>bool accepted = 2;</code>
   * @return The accepted.
   */
  boolean getAccepted();

  /**
   * <code>bool deduplicated = 3;</code>
   * @return The deduplicated.
   */
  boolean getDeduplicated();

  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @return A list containing the matchedPlatforms.
   */
  java.util.List<java.lang.String>
      getMatchedPlatformsList();
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @return The count of matchedPlatforms.
   */
  int getMatchedPlatformsCount();
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @param index The index of the element to return.
   * @return The matchedPlatforms at the given index.
   */
  java.lang.String getMatchedPlatforms(int index);
  /**
   * <code>repeated string matched_platforms = 4;</code>
   * @param index The index of the value to return.
   * @return The bytes of the matchedPlatforms at the given index.
   */
  com.google.protobuf.ByteString
      getMatchedPlatformsBytes(int index);

  /**
   * <pre>
   * accepted=false 时的原因（批量流中按条返回，不中断流）。
   * </pre>
   *
   * <code>string error = 5;</code>
   * @return The error.
   */
  java.lang.String getError();
  /**
   * <pre>
   * accepted=false 时的原因（批量流中按条返回，不中断流）。
   * </pre>
   *
   * <code>string error = 5;</code>
   * @return The bytes for error.
   */
  com.google.protobuf.ByteString
      getErrorBytes();
}
