// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface RetryPolicyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.RetryPolicy)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 max_attempts = 1;</code>
   * @return The maxAttempts.
   */
  int getMaxAttempts();

  /**
   * <pre>
   * 首次退避基数，指数增长 + 随机抖动
   * </pre>
   *
   * <code>int64 backoff_ms = 2;</code>
   * @return The backoffMs.
   */
  long getBackoffMs();
}
