// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

@com.google.protobuf.Generated
public interface SubscribeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:notify.v1.SubscribeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @return A list containing the topics.
   */
  java.util.List<java.lang.String>
      getTopicsList();
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @return The count of topics.
   */
  int getTopicsCount();
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  java.lang.String getTopics(int index);
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  com.google.protobuf.ByteString
      getTopicsBytes(int index);
}
