// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: notify/v1/notify.proto
// Protobuf Java Version: 4.36.1

package io.notifyhub.v1;

/**
 * Protobuf type {@code notify.v1.SubscribeRequest}
 */
@com.google.protobuf.Generated
public final class SubscribeRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:notify.v1.SubscribeRequest)
    SubscribeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 36,
      /* patch= */ 1,
      /* suffix= */ "",
      "SubscribeRequest");
  }
  // Use SubscribeRequest.newBuilder() to construct.
  private SubscribeRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private SubscribeRequest() {
    topics_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_SubscribeRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_SubscribeRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_SubscribeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.notifyhub.v1.SubscribeRequest.class, io.notifyhub.v1.SubscribeRequest.Builder.class);
  }

  public static final int TOPICS_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private com.google.protobuf.LazyStringArrayList topics_ =
      com.google.protobuf.LazyStringArrayList.emptyList();
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @return A list containing the topics.
   */
  public com.google.protobuf.ProtocolStringList
      getTopicsList() {
    return topics_;
  }
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @return The count of topics.
   */
  public int getTopicsCount() {
    return topics_.size();
  }
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @param index The index of the element to return.
   * @return The topics at the given index.
   */
  public java.lang.String getTopics(int index) {
    return topics_.get(index);
  }
  /**
   * <pre>
   * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
   * </pre>
   *
   * <code>repeated string topics = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the topics at the given index.
   */
  public com.google.protobuf.ByteString
      getTopicsBytes(int index) {
    return topics_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < topics_.size(); i++) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, topics_.getRaw(i));
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < topics_.size(); i++) {
        dataSize += computeStringSizeNoTag(topics_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getTopicsList().size();
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.notifyhub.v1.SubscribeRequest)) {
      return super.equals(obj);
    }
    io.notifyhub.v1.SubscribeRequest other = (io.notifyhub.v1.SubscribeRequest) obj;

    if (!getTopicsList()
        .equals(other.getTopicsList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTopicsCount() > 0) {
      hash = (37 * hash) + TOPICS_FIELD_NUMBER;
      hash = (53 * hash) + getTopicsList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static io.notifyhub.v1.SubscribeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static io.notifyhub.v1.SubscribeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static io.notifyhub.v1.SubscribeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.notifyhub.v1.SubscribeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code notify.v1.SubscribeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:notify.v1.SubscribeRequest)
      io.notifyhub.v1.SubscribeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_SubscribeRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_SubscribeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.notifyhub.v1.SubscribeRequest.class, io.notifyhub.v1.SubscribeRequest.Builder.class);
    }

    // Construct using io.notifyhub.v1.SubscribeRequest.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      topics_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.notifyhub.v1.NotifyProto.internal_static_notify_v1_SubscribeRequest_descriptor;
    }

    @java.lang.Override
    public io.notifyhub.v1.SubscribeRequest getDefaultInstanceForType() {
      return io.notifyhub.v1.SubscribeRequest.getDefaultInstance();
    }

    @java.lang.Override
    public io.notifyhub.v1.SubscribeRequest build() {
      io.notifyhub.v1.SubscribeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public io.notifyhub.v1.SubscribeRequest buildPartial() {
      io.notifyhub.v1.SubscribeRequest result = new io.notifyhub.v1.SubscribeRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(io.notifyhub.v1.SubscribeRequest result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        topics_.makeImmutable();
        result.topics_ = topics_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.notifyhub.v1.SubscribeRequest) {
        return mergeFrom((io.notifyhub.v1.SubscribeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.notifyhub.v1.SubscribeRequest other) {
      if (other == io.notifyhub.v1.SubscribeRequest.getDefaultInstance()) return this;
      if (!other.topics_.isEmpty()) {
        if (topics_.isEmpty()) {
          topics_ = other.topics_;
          bitField0_ |= 0x00000001;
        } else {
          ensureTopicsIsMutable();
          topics_.addAll(other.topics_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      java.util.Objects.requireNonNull(extensionRegistry);
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              ensureTopicsIsMutable();
              topics_.add(input.readStringRequireUtf8());
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringArrayList topics_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    private void ensureTopicsIsMutable() {
      if (!topics_.isModifiable()) {
        topics_ = new com.google.protobuf.LazyStringArrayList(topics_);
      }
      bitField0_ |= 0x00000001;
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @return A list containing the topics.
     */
    public com.google.protobuf.ProtocolStringList
        getTopicsList() {
      topics_.makeImmutable();
      return topics_;
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @return The count of topics.
     */
    public int getTopicsCount() {
      return topics_.size();
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @param index The index of the element to return.
     * @return The topics at the given index.
     */
    public java.lang.String getTopics(int index) {
      return topics_.get(index);
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @param index The index of the value to return.
     * @return The bytes of the topics at the given index.
     */
    public com.google.protobuf.ByteString
        getTopicsBytes(int index) {
      return topics_.getByteString(index);
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @param index The index to set the value at.
     * @param value The topics to set.
     * @return This builder for chaining.
     */
    public Builder setTopics(
        int index, java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureTopicsIsMutable();
      topics_.set(index, value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @param value The topics to add.
     * @return This builder for chaining.
     */
    public Builder addTopics(
        java.lang.String value) {
      java.util.Objects.requireNonNull(value);
      ensureTopicsIsMutable();
      topics_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @param values The topics to add.
     * @return This builder for chaining.
     */
    public Builder addAllTopics(
        java.lang.Iterable<java.lang.String> values) {
      ensureTopicsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, topics_);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearTopics() {
      topics_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
      bitField0_ = (bitField0_ & ~0x00000001);;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 支持通配符：`*` 匹配一段，`#` 匹配零或多段（以 `.` 分隔），如 "alert.*"、"logs.#"。
     * </pre>
     *
     * <code>repeated string topics = 1;</code>
     * @param value The bytes of the topics to add.
     * @return This builder for chaining.
     */
    public Builder addTopicsBytes(
        com.google.protobuf.ByteString value) {
      java.util.Objects.requireNonNull(value);
      checkByteStringIsUtf8(value);
      ensureTopicsIsMutable();
      topics_.add(value);
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:notify.v1.SubscribeRequest)
  }

  // @@protoc_insertion_point(class_scope:notify.v1.SubscribeRequest)
  private static final io.notifyhub.v1.SubscribeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.notifyhub.v1.SubscribeRequest();
  }

  public static io.notifyhub.v1.SubscribeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<SubscribeRequest>
      PARSER = new com.google.protobuf.AbstractParser<SubscribeRequest>() {
    @java.lang.Override
    public SubscribeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<SubscribeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<SubscribeRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public io.notifyhub.v1.SubscribeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

