# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from notifyhub.notify.v1 import notify_pb2 as notify_dot_v1_dot_notify__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in notify/v1/notify_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NotifyStub:
    """NotifyHub —— 多语言通知推送服务。
    本文件是唯一契约：服务端将来重写（Go/Rust/Zig）时不得变更既有字段的编号与语义。
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Publish = channel.unary_unary(
                '/notify.v1.Notify/Publish',
                request_serializer=notify_dot_v1_dot_notify__pb2.PublishRequest.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.PublishAck.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/notify.v1.Notify/Subscribe',
                request_serializer=notify_dot_v1_dot_notify__pb2.SubscribeRequest.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.Event.FromString,
                _registered_method=True)
        self.PublishStream = channel.stream_stream(
                '/notify.v1.Notify/PublishStream',
                request_serializer=notify_dot_v1_dot_notify__pb2.PublishRequest.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.PublishAck.FromString,
                _registered_method=True)
        self.UpsertPlatform = channel.unary_unary(
                '/notify.v1.Notify/UpsertPlatform',
                request_serializer=notify_dot_v1_dot_notify__pb2.PlatformConfig.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.PlatformConfig.FromString,
                _registered_method=True)
        self.ListPlatforms = channel.unary_unary(
                '/notify.v1.Notify/ListPlatforms',
                request_serializer=notify_dot_v1_dot_notify__pb2.Empty.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.PlatformList.FromString,
                _registered_method=True)
        self.RemovePlatform = channel.unary_unary(
                '/notify.v1.Notify/RemovePlatform',
                request_serializer=notify_dot_v1_dot_notify__pb2.PlatformRef.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.Empty.FromString,
                _registered_method=True)
        self.Ping = channel.unary_unary(
                '/notify.v1.Notify/Ping',
                request_serializer=notify_dot_v1_dot_notify__pb2.Empty.SerializeToString,
                response_deserializer=notify_dot_v1_dot_notify__pb2.Pong.FromString,
                _registered_method=True)


class NotifyServicer:
    """NotifyHub —— 多语言通知推送服务。
    本文件是唯一契约：服务端将来重写（Go/Rust/Zig）时不得变更既有字段的编号与语义。
    """

    def Publish(self, request, context):
        """发布通知：按路由推送到外部平台 + 广播给在线订阅者。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """订阅主题，服务端流式推送。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishStream(self, request_iterator, context):
        """批量发布（双向流：每收到一条请求，回执一条 Ack）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpsertPlatform(self, request, context):
        """用代码配置推送平台（运行时生效；重启后需重新注册，或写入配置文件）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPlatforms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemovePlatform(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Ping(self, request, context):
        """健康检查（无需鉴权）。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NotifyServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.PublishRequest.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.PublishAck.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.SubscribeRequest.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.Event.SerializeToString,
            ),
            'PublishStream': grpc.stream_stream_rpc_method_handler(
                    servicer.PublishStream,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.PublishRequest.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.PublishAck.SerializeToString,
            ),
            'UpsertPlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.UpsertPlatform,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.PlatformConfig.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.PlatformConfig.SerializeToString,
            ),
            'ListPlatforms': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPlatforms,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.Empty.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.PlatformList.SerializeToString,
            ),
            'RemovePlatform': grpc.unary_unary_rpc_method_handler(
                    servicer.RemovePlatform,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.PlatformRef.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.Empty.SerializeToString,
            ),
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=notify_dot_v1_dot_notify__pb2.Empty.FromString,
                    response_serializer=notify_dot_v1_dot_notify__pb2.Pong.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'notify.v1.Notify', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('notify.v1.Notify', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Notify:
    """NotifyHub —— 多语言通知推送服务。
    本文件是唯一契约：服务端将来重写（Go/Rust/Zig）时不得变更既有字段的编号与语义。
    """

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notify.v1.Notify/Publish',
            notify_dot_v1_dot_notify__pb2.PublishRequest.SerializeToString,
            notify_dot_v1_dot_notify__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/notify.v1.Notify/Subscribe',
            notify_dot_v1_dot_notify__pb2.SubscribeRequest.SerializeToString,
            notify_dot_v1_dot_notify__pb2.Event.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/notify.v1.Notify/PublishStream',
            notify_dot_v1_dot_notify__pb2.PublishRequest.SerializeToString,
            notify_dot_v1_dot_notify__pb2.PublishAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpsertPlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notify.v1.Notify/UpsertPlatform',
            notify_dot_v1_dot_notify__pb2.PlatformConfig.SerializeToString,
            notify_dot_v1_dot_notify__pb2.PlatformConfig.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPlatforms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notify.v1.Notify/ListPlatforms',
            notify_dot_v1_dot_notify__pb2.Empty.SerializeToString,
            notify_dot_v1_dot_notify__pb2.PlatformList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemovePlatform(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notify.v1.Notify/RemovePlatform',
            notify_dot_v1_dot_notify__pb2.PlatformRef.SerializeToString,
            notify_dot_v1_dot_notify__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/notify.v1.Notify/Ping',
            notify_dot_v1_dot_notify__pb2.Empty.SerializeToString,
            notify_dot_v1_dot_notify__pb2.Pong.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
